##### Importing Libraries

In [35]:
import pandas as pd
import numpy as np

In [36]:
import matplotlib.pyplot as plt
import seaborn as sns

##### Data Collectiona nd data cleaning

In [37]:
df=pd.read_csv("../data/dataset.csv")

df.head(2)

                                                Text         Label Types
0  Ten outside soon doctor shake everyone treatme...  Not-Bullying   NaN
1  my life has come to a standstill and at this p...  Not-Bullying   NaN

In [38]:
df.shape

(8452, 3)

there are total 8452 rows and 3 columsn

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8452 entries, 0 to 8451
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    8452 non-null   object
 1   Label   8450 non-null   object
 2   Types   4825 non-null   object
dtypes: object(3)
memory usage: 198.2+ KB

In [40]:
df.isnull().sum()

Text        0
Label       2
Types    3627
dtype: int64

dropping types column as we want to predict the whether the text is harrasment or normal

In [41]:
df.drop('Types',axis=1,inplace=True)

In [42]:
df.head(2)

                                                Text         Label
0  Ten outside soon doctor shake everyone treatme...  Not-Bullying
1  my life has come to a standstill and at this p...  Not-Bullying

In [43]:
df.isnull().sum()

Text     0
Label    2
dtype: int64

In [44]:
df.columns=df.columns.str.lower()

In [45]:
df[df['label'].isnull()]

                                         text label
1303                    Wow, stunning photo!"   NaN
2055  Your posts always brighten up my feed!"   NaN

In [46]:
df['label'].value_counts()

label
Bullying          3020
Not-Bullying      2752
Bullying          1805
Not- Bullying      270
Not-Bullying       252
Not Bullying       242
Not-Bulllying       31
Not-Bulying         30
Not-Bulyying        21
Not - Bullying       5
Not -Bullying        4
Not -Bullying        4
Not bullying         4
Bullying.            3
Bullyinfg            3
Bullyiing            1
Not- Bullying        1
Bullyibg             1
Bullying             1
Name: count, dtype: int64

In [47]:
df['label']=df['label'].str.strip().str.lower()

df['label'].value_counts()

label
bullying          4826
not-bullying      3004
not- bullying      271
not bullying       246
not-bulllying       31
not-bulying         30
not-bulyying        21
not -bullying        8
not - bullying       5
bullying.            3
bullyinfg            3
bullyiing            1
bullyibg             1
Name: count, dtype: int64

In [48]:
label_map = {
    'bullying': 'harassment',
    'not-bullying': 'normal',
    'not- bullying': 'normal',
    'not bullying': 'normal',
    'not-bulllying': 'normal',

    'not-bulying': 'normal',
    'not-bulyying': 'normal',

    'not -bullying': 'normal',

    'not - bullying': 'normal',

    'bullying.': 'harassment',

    'bullyinfg': 'harassment',

    'bullyiing':'harassment',

    'bullyibg':'harassment'
}

In [49]:
df['label']=df['label'].map(label_map)

df['label'].value_counts()

label
harassment    4834
normal        3616
Name: count, dtype: int64

In [51]:
df.isnull().sum()

text     0
label    2
dtype: int64

In [50]:
df[df['label'].isnull()]

                                         text label
1303                    Wow, stunning photo!"   NaN
2055  Your posts always brighten up my feed!"   NaN

In [52]:
df.dropna(inplace=True)

In [53]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [54]:
df.duplicated().sum()

np.int64(2375)

In [57]:
df[df.duplicated()]

                                                   text       label
40                     Wishing my arena partner was on.      normal
113                                 I want to buy a car      normal
194   This isn't going to work, because we've all go...      normal
195                       You look absolutely stunning!      normal
196                     Your smile brightens up my day!      normal
...                                                 ...         ...
8404        You'll regret having crossed me, I promise.  harassment
8405                Nobody can resist me, not even you.  harassment
8421  The excessive workload and unreasonable demand...  harassment
8433  Why does god require you to defend Islam, kill...      normal
8442  Why does god require you to defend Islam, kill...  harassment

[2375 rows x 2 columns]

In [58]:
df[df['text']=='I want to buy a car']

                     text   label
88    I want to buy a car  normal
113   I want to buy a car  normal
293   I want to buy a car  normal
1867  I want to buy a car  normal
3080  I want to buy a car  normal
3106  I want to buy a car  normal
3289  I want to buy a car  normal
4449  I want to buy a car  normal
4474  I want to buy a car  normal

In [59]:
df.drop_duplicates(inplace=True)

In [60]:
df.isnull().sum()

text     0
label    0
dtype: int64

##### Text preprocessing

In [66]:

for i in range(len(df)):
    print(df['text'].iloc[i])

Ten outside soon doctor shake everyone treatment seat radio land.
my life has come to a standstill and at this point.
girl this nigga make me sick to my stomach
I wanna fuck you
Oh hey, you should be ashamed of your disgusting self
Haha isn't route running part of the position? People are dumb. But fuck edelman! He just looks like he says
Racism is when u select yur white clothes to wash first before the black and colored ones
Who are islamists? Those who fully follow the teachings of Muhammed found in the Quran and Hadiths
Male action movies...ehhhh @That_Damn_Ram Not sexist but female action movies...ehhhh
Wishing my arena partner was on.
I hope this round humbled the girls, they can't cook
Ha-ha-ha-ha-ha! Islam is against evil
Thanks to everyone that came out to walk with us and San Benito Bully dog  group.
Dealing with harassment
you not only a nigger, you're a dumb nigger. Fuck you and your riots. You want war?
I hate your job too.
Get fucking real dude.
Heh. Fuck 'em WHERE?!?
You know there are people out there who like but don't listen to old school.
Really miss my classmates n schoolmates. See you all soon people
Let's talk about what it means to be a victim
no one ever help.me like my bully
My friends and me got called niggers by this Mexican chick .
Idiot I'm talking about Halal Products not Muslims. Are you saying Halal products means Muslims ?
As is said,the basic criteria to be a muslim is to be a chootiya and become katua, that makes you a perfect idiot and follower of Allah
Israel and US have the same enemies.
Bangladesh is a looser country
Bangladesh are allout o 100 runs.
I love sunny leone and sweet children's
Me your big friend from bangladesh
i m not tired babe.....i have been flying like clouds in ur mind
Hahaha!  Well take care then.
Heroalom is fool of bangladesh actor
Yay! Yaya on the dance floor I like the way she is confident about her body
Bangladesh is a so beautiful Country
HOLY FUCK! GIRL YOU CANT DO STUFF LIKE THAT!
Son of a bitch!
r u a drty slut?
You are a dirty mind people.
Looks like beatiful
See you all soon Bebs.
He killed him
Oil your own machine.
she loves flower
you are a fatty fat fat
Maram wanted to research the roots of her
You look like a gypsy. Sorry I'm not sorry.
Walked out of the shelter with no puppy, but now I have a date.
wait your fb is banned now
Heroalom er cehara dekte akebare nispap baccha
The Muslim Brotherhood President of Egypt was removed in 2013 by Obama You guys are idiots.
To RESTRICT Jihadis-Terrorists CONSPIRING Ghazwa-e-Hind Dar-ul-Harb JIHAD against Hindus-Hindutva-Hindusthan-Humanity
Hindus are son of bitches
Bnp are not power to the election
Hey girl your sexy figure is so nice
I love my country
 None of them can show anything in her past but current plans.
Have not seen a white girl/boy act as dumb or hateful as a nigger or beaner since election but fuck white people we are racists!
kimjonun is a dangerous person
Shut the fuck up, Red, you dumb nigger
Fuck u baby
Looks like pretty
Sister, your baby is so cute
I fucking forgot it. So mad.
 the tourists suck worse
she sucks.
FUCK ME !
Tui kon bal hoicos
Now you are finished
You cannot Salat
I got my system working in here
you are a fuck boy lusser
Hate them.
I'm sure you are a loser
I want fuck you
You are mine
you are killed him
I think feeling is one of ur first senses to go
Racism in this country is what's driving us all nuts
Let the law do their diligence. You morons!
Your friends are all stupid niggers so how are they any help to you?!
Wow sexy girl.
One night stay with you bby..
Which is why he was fired by Muslim people
I'm not sure about the universe.
Mondir vanish to the world.
I like it
I want to buy a car
I want to talk with you
Hot Figure
He likes to paint by himself.
You are a poor people
killed him buddis people
I want to be a computer engineer.
Brazil is not a country in Europe.
I want to do something.
You should go take it from him.
We borrowed her car.
Julie talks very fast.
We see them every week.
When does the train usually leave?
How cruel you are
I will take it from you.
Why do you talk so badly?
The country will not improve by you
What Muslim are you talking about you idiot
You figure is to much hot
I kiss u.
Take it easy
Don't worry
whats the fuck girl
U are poor people
You are my wife
She looks like a bitch
He drank alcohol and beat his wife
Eid day are the bad day of month
say earth flat like a carpet is an idiot.
the prophet Muhamad s.w.s declared islam afull religion
Sexy
Tor cehara na dekhay vlo
Why do Muslims force women to cover up and stay at home?
I want to do this
no kidding!
Damn good
I love this place
Fuck of this
you are a lier
Thanks kitty
you are third gender people
waiting for you
I hate you
Hey girl i sleep at a Night
I hate Lucky Charms
Nuclear weapons pose a threat to everyone.
The police have to take any terrorist
It is hoped that the kidnappers will not carry out their threat to kill the hostages.
Three main line railway stations were closed
The key witness for the prosecution was offered police protection after she received
 If ur still not Muslim till the day of judgment,  shock u would be to learn that Allah is the one and only true God
Expect trouble this weekend from the radical Christians that support him.
Just another day at the office.
Dawg I want this bitch to suffer
Answer my claims idiot. You sent Qur'an verses talking about all Muslims going to Hell.
How about you stop asking questions lil nigga
To divide India on the ground of Islam and Jinna ordered for Direct Ac Consequently  murder of Hindus was done
Watching Movie
Your noods is virul
now I know what I will watch tomorrow while eating
Haha you are a bad student
The video is so nice!
This video is worth going viral.
You are the next tik tok super star, my friend.
I can’t believe it’s you, keep growing, keep doing.
just love your TikTok videos, they are quite entertaining
.. They are so cute . . I feel so sorry to hear that people think all of Thai K-POP fan hate them because It's not
Hey girl per night 1000 tk
you are a foolish
I made some orchestral music
 Too bad about those hurt by it or unprotected by it, right?
Tattoo that shit on your forehead.
 i really appreciate the kind words from you. i'm a big admirer of your voice
This isn't going to work, because we've all got a maturity greater than 12 year olds
You look absolutely stunning!
Your smile brightens up my day!
This post made me smile. Thanks for sharing!
You always have the coolest adventures!
Thank you for your help. You're a lifesaver!
I'm grateful to have you in my life.
Yeah thats picture is as like hero alom
Your hard work and dedication are truly admirable.
If you ever need a hand, just let me know."
I'm here to support you in any way I can.
Don't hesitate to reach out if you need anything.
Happy Birthday! May this year be filled with joy and success.
Another year wiser and more fabulous. Enjoy your day!
Your birthday is a reminder of how special you are. Have a fantastic celebration!
When someone shares a personal story:
Your photography skills are exceptional; each picture tells a story
Your leadership style is inspiring; you lead by example.
The way you handle challenges and motivate your team is admirable.
You bring out the best in everyone you work with. A true leader!
Your talent knows no bounds!
You have an incredible way with words.
m here for you, no matter what. We'll get through this together."
You're incredibly strong, and I believe in your ability to overcome this.
Sending you all the positive vibes and strength you need right now.
Recognizing someone's creativity:
Your artistic talents are a true gift to the world. Keep creating!
Your love story is beautiful, and your wedding was a magical celebration.
May your journey together be full of wonderful adventures and cherished moments.
I'm always amazed by your artistic talents.
Your passion for [insert interest] is inspiring
Believe in yourself—you've got this!
Don't give up; you're stronger than you think
Your dedication and hard work are paying off. Keep it up!
You've reached a milestone that many aspire to. Well done!
This accomplishment is a testament to your determination and talent
I'm here for you, no matter what.
Your resilience is awe-inspiring.
Their collection of movies are adult types
You need a very hot dress
You looking too much hot
You are so raw and so beautiful
Even as a troll you are a pathetic failure.
This is way past George Floyd.
I think feeling is one of ur first senses to go
Let the law do their diligence. You morons!
The police have to take any terrorist
Nuclear weapons pose a threat to everyone.
It is hoped that the kidnappers will not carry out their threat to kill the hostages.
Three main line railway stations were closed
The key witness for the prosecution was offered police protection after she received
seriously can’t stop watching this
Fuck of
what is your size?
Congratulations on your well-deserved success!
You've worked so hard for this moment—enjoy it!
Your achievements continue to inspire us all.
I knew you could do it! Way to go!
Thank you for sharing your story; it's truly inspiring.
Your experiences resonate with so many of us. You're not alone.
Your courage in sharing this is commendable. You're making a difference.
Encouragement for a new endeavor:
me andd you lets go to the club
I'm here to listen if you ever need to talk.
I can imagine how challenging that must be.
Sending you love and positive vibes during this tough time.
Your feelings are valid, and I'm here to support you
You rocked the stage! What a fantastic performance!
Your artistic talents are a true gift to the world. Keep creating!"
Your imagination knows no bounds. I'm constantly amazed by your creativity.
Your work is a masterpiece, and I'm excited to see what you create next.
Encouraging personal growth and self-improvement:
I was captivated from start to finish. Well done!
When someone shares good news:
Starting something new can be intimidating, but I have faith in your abilities.
Embrace this opportunity with confidence; you have what it takes.
I can't wait to see where this journey takes you. Go for it!
One night stay with me please
Your commitment to self-improvement is inspiring. Keep evolving!
Each day is a chance to become a better version of yourself. You're doing great!
Your dedication to personal growth is an investment in your future success.
I'm so happy for you! What wonderful news!
Your success brings joy to all of us.
This is the best news I've heard all day!
Your positivity is contagious!
Hot girls
how lame the politicals are
It can't happed without our sex night
The people are too much talkative
Congratulations on your well-deserved promotion! Your hard work paid off."
Your contributions to the team are exceptional. You're an asset to our organization.
Your success sets a high standard for all of us to aspire to.
Expressing gratitude for friendship:
I'm lucky to have a friend like you. Thank you for always being there.
Your friendship means the world to me. I cherish our moments together.
In the tapestry of life, you're one of the most colorful threads.
People are irresponsible for theie post
The post of the manager is harmful for the society
The Society can do everything for their bad things
Social people are too much bad
hahaha the memes is like as you
This photo is absolutely breathtaking. You have a great eye for capturing moments.
You've captured the essence of the moment perfectly.
Your photography skills are exceptional; each picture tells a story.
Expressing admiration for someone's wisdom:
Lets talk about sex
Lets talk abou the rubbish team
your ass is too much hot
The mango people are very bad
Your insights always provide a fresh perspective. I learn so much from you.
Your wisdom is like a guiding light in my life.
I'm continually inspired by your depth of knowledge and insight.
Praising someone's leadership:
You are a rabbish
Her working level is too much low
I love how that actually looks like he's
what the fuck
wow sexy
Thats great
Students League are fuck of
HATE getting the last word. That's why they follow you around expectantly after an argument, hoping you'll say something.
stupid video George Z had to do that in self defense.
Did your father Humayun Kabir's sperm enter your mother during your birth process?
No more Viagra for Dhazhvong. Destroy all these kulkhankiras.
A stupid one.
He should be set on fire.
Shoes should be worn.
Now I understand why they slaughter you.
Kick the whore
Shoot her wherever you find her, you atheist girl..

Tui kuttar bacca
a Caucasian male can be called white,
He could be a Caucasian from England, Wales, Scotland, Northern Ireland, or any other number of countries.
Seriously, how am I the only person that caught this?
party almost over
Our favourite teams pushed to the limit
nationality is a legal identification of a person in international law, establishing the person as a subject,
We need this information to make sure that we’re giving equal opportunities to all candidates.“
Those people should be suspended.
This is really insulting to say that
These comments are very stupid, idiotic, scary and fake
Imagine how kids would feel reading this comment,
Appear tonight and kill me?
Your new job is a testament to your skills and dedication. Congratulations!"
Wishing you success and fulfillment in this exciting new chapter of your career.
The company is lucky to have someone as talented as you. Well done!
excuse the crimes of Islam rather than get rid of them.
I have no problem with Hinduism, Christianity, Tao, Judaism, Buddhism or atheism
 But Islam hates all non-Muslims.
Not others
Follow your dreams and never stop pursuing your passion. You've got this!"
Your passion is contagious, and I believe in your ability to achieve greatness.
Don't be afraid to chase what sets your soul on fire. The world needs your passion.
you are looking really hot in the photo
Or religion er thik nai. or god bhul god
you are looking beautiful
Every dish you make is a culinary masterpiece. You're a fantastic chef!"
Your cooking always leaves me craving for more. It's simply delicious!
You have a knack for turning simple ingredients into gourmet delights.
Your creativity knows no bounds, and I can't wait to see your project come to life."
You're making something incredible, and I'm here to support you every step of the way.
Your project has the potential to inspire and amaze. Keep up the fantastic work!
Celebrating a milestone or anniversary:
sexy lady
Sucks you girls
I love u
Does N.e.bodyelse Hear her Crazy ass Screamin
There are so many things that are incorrect with your comment it's unbelievable. Guns don't kill people.
hahah my boyfriend showed this song to me I love it Me tooo Is she having a seizure.
 Call girl is a whore PH is real ugly what's f*king with rihanna right now?
i love little sooyoungyuriyoona and taeyeon
better country such as Rhodesia?
seriously so funny I really love this.
 I'm not sexist but fuck if you're a woman and you can't Cook get your shit together.
There's some very hate able teams this year
 The dignity of that Peshmerga as he faced death was remarkably heroic.
actually check if any of these people could cook?
 I thought of a really funny joke and I promise I'm not sexist but I have to say it.
i've been told i'm pretty good at drumming up suspense.
I was hoping someone would say "let's get Kat out, we'll score a 10"
I have no idea how anyone is seeing blue at all.
We can't even fucking ride bikes now?
That guy kept going for a while, too. I think he proposed.
You thought meatballs was going to win people
Motherfuck
R kto ber kre dekhbi?
Election is not to fair
This is coming from the same group that claimed
 Because being female is the *only* quality a person should be judged on. Got it.
the only thing i wish, i wish a nigga would
You saudias are not friends of Muslim idiots cheapless people
This little light of mine, I'm gonna let it shine. I'm Live now come say hi.
He is a bitch.  Plain and simple.  Every game same shit.
It's so scary!
 Muslim mob violence against Hindus in Bangladesh continues in 2014.
Palestine Islamophobia is like the idea of Naziphobia. Islam is a religion of hate and it must be outlawed.
Relig Islam invaded and conquered 2/3 of Christiandom before any Christian crusades in response.
Do you approve of your pedophile prophet raping a 9 year old girl, like it says in 7 hadith?
Problem with vile Muslims is that they try to rationalize &amp;
 I had to manually block her.
 This story is now ancient history and was never true to begin with.
IsraeliRegime Notice how most of the contributions are from Persians, not Arabs, and are despite Islam.
 I think your Muslim friends are raping girls around the world.
How can someone fuck up cous cous for fuck sake
STOP SAYING CYBER HACKERS
Happy anniversary! Here's to many more years of love and happiness."
Milestones like these are a testament to your dedication and love. Congratulations!
May this special day be a reminder of all the beautiful moments you've shared.
You look like as a hero alom
"Gag" gifts such as sex toys and merchandise
Political criticism, also referred to as political commentary
Your patience in challenging situations is a virtue many aspire to. You handle things with grace."
I'm always impressed by how composed and patient you are, even in the toughest times.
Your ability to remain calm and patient is a true superpower.
 Mohammed was a pedophile, murderer
the prophet Mohammed is something I've preached for 15
"You are a liar."
Whistling, cat calls, kissing or smacking sounds
"fuck you both"
Spreading rumors about a person's sex life
Your dedication to making a difference in the world is admirable. Keep fighting for what you believe in."
The impact you're making in your community is truly inspiring. Thank you for your commitment.
Your efforts to raise awareness and drive change are changing lives for the better.
Your writing is so captivating; I get lost in every word."
You have a gift for storytelling that brings characters and worlds to life.
Your words have a way of touching hearts and sparking imagination.
Did they make this splatfest because we're near Valentine's Day or something?
We had jasson garret and joe judge calling plays dumb fuck. everything in the NFL nowadays is about coaching.
Cause usually it's chocolate related..
Every day is a new opportunity to make a positive impact on the world.
"You have the ability to achieve anything you set your mind to.
"Life is full of wonderful surprises waiting for you.
"Your kindness and compassion inspire those around you.
"Challenges are opportunities in disguise. You've got this!
"Today is a gift; that's why it's called the present.
"Your smile has the power to light up even the darkest of days.
I believe in a relatively equal society,
Challenges are opportunities in disguise. You've got this!"
Today is a gift; that's why it's called the present.
very bad idea this is
Your smile has the power to light up even the darkest of days.
The world is a better place because you're in it.
Success is a journey, not a destination. Enjoy the ride.
Believe in yourself, and amazing things will happen.
You are capable of achieving greatness through hard work and determination."
Every setback is a setup for a comeback.
Your positive attitude is a magnet for success and happiness.
Life's challenges are opportunities for growth and learning.
Your presence makes every moment more meaningful.
Your unique qualities and strengths make you extraordinary.
The world is full of beauty, and you have the eyes to see it.
You are a beacon of hope and positivity for those around you.
Every day is a chance to create a better tomorrow.
You have the power to inspire and uplift others with your words and actions
the level of threat has a greater impact than regime type on the likelihood of political repression
 Islam is inhuman and must be outlawed.

In [67]:
import re

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer=WordNetLemmatizer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [79]:
stopwords_list=set(stopwords.words('english'))

In [80]:
stopwords_list

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [81]:
from nltk.corpus import wordnet
def get_wordnet_pos(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [83]:
corpus=[]

for i in range(len(df)):
    cleaned=re.sub(r'[^a-zA-Z]',' ',df['text'].iloc[i])

    cleaned=cleaned.lower()

    cleaned=cleaned.split()
    
    pos_tags=nltk.pos_tag(cleaned)

    cleaned=[lemmatizer.lemmatize(word,pos=get_wordnet_pos(pos)) for word,pos in pos_tags if word not in stopwords_list]
    cleaned=' '.join(cleaned)

    corpus.append(cleaned)

In [ ]:
corpus

['ten outside soon doctor shake everyone treatment seat radio land',
 'life come standstill point',
 'girl nigga make sick stomach',
 'wanna fuck',
 'oh hey ashamed disgust self',
 'haha route run part position people dumb fuck edelman look like say',
 'racism u select yur white clothes wash first black colored one',
 'islamist fully follow teaching muhammed find quran hadith',
 'male action movie ehhhh damn ram sexist female action movie ehhhh',
 'wish arena partner',
 'hope round humble girl cook',
 'ha ha ha ha ha islam evil',
 'thanks everyone come walk u san benito bully dog group',
 'deal harassment',
 'nigger dumb nigger fuck riot want war',
 'hate job',
 'get fucking real dude',
 'heh fuck em',
 'know people like listen old school',
 'really miss classmate n schoolmate see soon people',
 'let talk mean victim',
 'one ever help like bully',
 'friend get call nigger mexican chick',
 'idiot talk halal product muslim say halal product mean muslim',
 'say basic criterion muslim chootiya become katua make perfect idiot follower allah',
 'israel u enemy',
 'bangladesh loose country',
 'bangladesh allout run',
 'love sunny leone sweet child',
 'big friend bangladesh',
 'tire babe fly like cloud ur mind',
 'hahaha well take care',
 'heroalom fool bangladesh actor',
 'yay yaya dance floor like way confident body',
 'bangladesh beautiful country',
 'holy fuck girl cant stuff like',
 'son bitch',
 'r u drty slut',
 'dirty mind people',
 'look like beatiful',
 'see soon bebs',
 'kill',
 'oil machine',
 'love flower',
 'fatty fat fat',
 'maram want research root',
 'look like gypsy sorry sorry',
 'walk shelter puppy date',
 'wait fb ban',
 'heroalom er cehara dekte akebare nispap baccha',
 'muslim brotherhood president egypt remove obama guy idiot',
 'restrict jihadis terrorist conspire ghazwa e hind dar ul harb jihad hindu hindutva hindusthan humanity',
 'hindu son bitch',
 'bnp power election',
 'hey girl sexy figure nice',
 'love country',
 'none show anything past current plan',
 'see white girl boy act dumb hateful nigger beaner since election fuck white people racist',
 'kimjonun dangerous person',
 'shut fuck red dumb nigger',
 'fuck u baby',
 'look like pretty',
 'sister baby cute',
 'fuck forget mad',
 'tourist suck bad',
 'suck',
 'fuck',
 'tui kon bal hoicos',
 'finish',
 'cannot salat',
 'get system work',
 'fuck boy lusser',
 'hate',
 'sure loser',
 'want fuck',
 'mine',
 'kill',
 'think feeling one ur first sense go',
 'racism country drive u nut',
 'let law diligence moron',
 'friend stupid nigger help',
 'wow sexy girl',
 'one night stay bby',
 'fire muslim people',
 'sure universe',
 'mondir vanish world',
 'like',
 'want buy car',
 'want talk',
 'hot figure',
 'like paint',
 'poor people',
 'kill buddis people',
 'want computer engineer',
 'brazil country europe',
 'want something',
 'go take',
 'borrow car',
 'julie talk fast',
 'see every week',
 'train usually leave',
 'cruel',
 'take',
 'talk badly',
 'country improve',
 'muslim talk idiot',
 'figure much hot',
 'kiss u',
 'take easy',
 'worry',
 'whats fuck girl',
 'u poor people',
 'wife',
 'look like bitch',
 'drink alcohol beat wife',
 'eid day bad day month',
 'say earth flat like carpet idiot',
 'prophet muhamad w declare islam afull religion',
 'sexy',
 'tor cehara na dekhay vlo',
 'muslim force woman cover stay home',
 'want',
 'kidding',
 'damn good',
 'love place',
 'fuck',
 'li',
 'thanks kitty',
 'third gender people',
 'wait',
 'hate',
 'hey girl sleep night',
 'hate lucky charm',
 'nuclear weapon pose threat everyone',
 'police take terrorist',
 'hop kidnapper carry threat kill hostage',
 'three main line railway station close',
 'key witness prosecution offer police protection receive',
 'ur still muslim till day judgment shock u would learn allah one true god',
 'expect trouble weekend radical christian support',
 'another day office',
 'dawg want bitch suffer',
 'answer claim idiot send qur verse talk muslim go hell',
 'stop ask question lil nigga',
 'divide india ground islam jinna order direct ac consequently murder hindu do',
 'watch movie',
 'noods virul',
 'know watch tomorrow eat',
 'haha bad student',
 'video nice',
 'video worth go viral',
 'next tik tok super star friend',
 'believe keep grow keep',
 'love tiktok video quite entertaining',
 'cute feel sorry hear people think thai k pop fan hate',
 'hey girl per night tk',
 'foolish',
 'make orchestral music',
 'bad hurt unprotected right',
 'tattoo shit forehead',
 'really appreciate kind word big admirer voice',
 'go work get maturity great year old',
 'look absolutely stun',
 'smile brighten day',
 'post make smile thanks share',
 'always coolest adventure',
 'thank help lifesaver',
 'grateful life',
 'yeah thats picture like hero alom',
 'hard work dedication truly admirable',
 'ever need hand let know',
 'support way',
 'hesitate reach need anything',
 'happy birthday may year fill joy success',
 'another year wiser fabulous enjoy day',
 'birthday reminder special fantastic celebration',
 'someone share personal story',
 'photography skill exceptional picture tell story',
 'leadership style inspire lead example',
 'way handle challenge motivate team admirable',
 'bring best everyone work true leader',
 'talent know bound',
 'incredible way word',
 'matter get together',
 'incredibly strong believe ability overcome',
 'send positive vibe strength need right',
 'recognize someone creativity',
 'artistic talent true gift world keep create',
 'love story beautiful wedding magical celebration',
 'may journey together full wonderful adventure cherish moment',
 'always amaze artistic talent',
 'passion insert interest inspire',
 'believe get',
 'give strong think',
 'dedication hard work pay keep',
 'reach milestone many aspire well do',
 'accomplishment testament determination talent',
 'matter',
 'resilience awe inspire',
 'collection movie adult type',
 'need hot dress',
 'look much hot',
 'raw beautiful',
 'even troll pathetic failure',
 'way past george floyd',
 'think feeling one ur first sense go',
 'let law diligence moron',
 'police take terrorist',
 'nuclear weapon pose threat everyone',
 'hop kidnapper carry threat kill hostage',
 'three main line railway station close',
 'key witness prosecution offer police protection receive',
 'seriously stop watching',
 'fuck',
 'size',
 'congratulation well deserve success',
 'work hard moment enjoy',
 'achievement continue inspire u',
 'know could way go',
 'thank share story truly inspiring',
 'experience resonate many u alone',
 'courage share commendable make difference',
 'encouragement new endeavor',
 'andd let go club',
 'listen ever need talk',
 'imagine challenging must',
 'send love positive vibe tough time',
 'feeling valid support',
 'rock stage fantastic performance',
 'artistic talent true gift world keep create',
 'imagination know bound constantly amaze creativity',
 'work masterpiece excite see create next',
 'encourage personal growth self improvement',
 'captivate start finish well do',
 'someone share good news',
 'start something new intimidate faith ability',
 'embrace opportunity confidence take',
 'wait see journey take go',
 'one night stay please',
 'commitment self improvement inspire keep evolve',
 'day chance become good version great',
 'dedication personal growth investment future success',
 'happy wonderful news',
 'success bring joy u',
 'best news hear day',
 'positivity contagious',
 'hot girl',
 'lame politicals',
 'happed without sex night',
 'people much talkative',
 'congratulation well deserve promotion hard work pay',
 'contribution team exceptional asset organization',
 'success set high standard u aspire',
 'express gratitude friendship',
 'lucky friend like thank always',
 'friendship mean world cherish moment together',
 'tapestry life one colorful thread',
 'people irresponsible theie post',
 'post manager harmful society',
 'society everything bad thing',
 'social people much bad',
 'hahaha meme like',
 'photo absolutely breathtaking great eye capture moment',
 'capture essence moment perfectly',
 'photography skill exceptional picture tell story',
 'express admiration someone wisdom',
 'let talk sex',
 'let talk abou rubbish team',
 'as much hot',
 'mango people bad',
 'insight always provide fresh perspective learn much',
 'wisdom like guide light life',
 'continually inspire depth knowledge insight',
 'praise someone leadership',
 'rabbish',
 'work level much low',
 'love actually look like',
 'fuck',
 'wow sexy',
 'thats great',
 'student league fuck',
 'hate get last word follow around expectantly argument hop say something',
 'stupid video george z self defense',
 'father humayun kabir sperm enter mother birth process',
 'viagra dhazhvong destroy kulkhankiras',
 'stupid one',
 'set fire',
 'shoe wear',
 'understand slaughter',
 'kick whore',
 'shoot wherever find atheist girl',
 'tui kuttar bacca',
 'caucasian male call white',
 'could caucasian england wale scotland northern ireland number country',
 'seriously person catch',
 'party almost',
 'favourite team push limit',
 'nationality legal identification person international law establish person subject',
 'need information make sure give equal opportunity candidate',
 'people suspend',
 'really insulting say',
 'comment stupid idiotic scary fake',
 'imagine kid would feel read comment',
 'appear tonight kill',
 'new job testament skill dedication congratulation',
 'wish success fulfillment exciting new chapter career',
 'company lucky someone talented well do',
 'excuse crime islam rather get rid',
 'problem hinduism christianity tao judaism buddhism atheism',
 'islam hate non muslim',
 'others',
 'follow dream never stop pursue passion get',
 'passion contagious believe ability achieve greatness',
 'afraid chase set soul fire world need passion',
 'look really hot photo',
 'religion er thik nai god bhul god',
 'look beautiful',
 'every dish make culinary masterpiece fantastic chef',
 'cooking always leave crave simply delicious',
 'knack turn simple ingredient gourmet delight',
 'creativity know bound wait see project come life',
 'make something incredible support every step way',
 'project potential inspire amaze keep fantastic work',
 'celebrate milestone anniversary',
 'sexy lady',
 'suck girls',
 'love u',
 'n e bodyelse hear crazy as screamin',
 'many thing incorrect comment unbelievable gun kill people',
 'hahah boyfriend show song love tooo seizure',
 'call girl whore ph real ugly f king rihanna right',
 'love little sooyoungyuriyoona taeyeon',
 'well country rhodesia',
 'seriously funny really love',
 'sexist fuck woman cook get shit together',
 'hate able team year',
 'dignity peshmerga face death remarkably heroic',
 'actually check people could cook',
 'thought really funny joke promise sexist say',
 'tell pretty good drum suspense',
 'hop someone would say let get kat score',
 'idea anyone see blue',
 'even fuck ride bike',
 'guy keep go think propose',
 'think meatball go win people',
 'motherfuck',
 'r kto ber kre dekhbi',
 'election fair',
 'come group claim',
 'female quality person judge got',
 'thing wish wish nigga would',
 'saudias friend muslim idiot cheapless people',
 'little light mine gonna let shine live come say hi',
 'bitch plain simple every game shit',
 'scary',
 'muslim mob violence hindu bangladesh continue',
 'palestine islamophobia like idea naziphobia islam religion hate must outlaw',
 'relig islam invade conquer christiandom christian crusade response',
 'approve pedophile prophet rap year old girl like say hadith',
 'problem vile muslim try rationalize amp',
 'manually block',
 'story ancient history never true begin',
 'israeliregime notice contribution persian arab despite islam',
 'think muslim friend rap girl around world',
 'someone fuck cous cous fuck sake',
 'stop say cyber hacker',
 'happy anniversary many year love happiness',
 'milestone like testament dedication love congratulation',
 'may special day reminder beautiful moment share',
 'look like hero alom',
 'gag gift sex toy merchandise',
 'political criticism also refer political commentary',
 'patience challenge situation virtue many aspire handle thing grace',
 'always impress composed patient even tough time',
 'ability remain calm patient true superpower',
 'mohammed pedophile murderer',
 'prophet mohammed something preach',
 'liar',
 'whistle cat call kiss smack sound',
 'fuck',
 'spread rumor person sex life',
 'dedication make difference world admirable keep fighting believe',
 'impact make community truly inspiring thank commitment',
 'effort raise awareness drive change change life good',
 'writing captivate get lose every word',
 'gift storytelling bring character world life',
 'word way touch heart spark imagination',
 'make splatfest near valentine day something',
 'jasson garret joe judge call play dumb fuck everything nfl nowadays coach',
 'cause usually chocolate relate',
 'every day new opportunity make positive impact world',
 'ability achieve anything set mind',
 'life full wonderful surprise wait',
 'kindness compassion inspire around',
 'challenge opportunity disguise get',
 'today gift call present',
 'smile power light even dark day',
 'believe relatively equal society',
 'challenge opportunity disguise get',
 'today gift call present',
 'bad idea',
 'smile power light even dark day',
 'world good place',
 'success journey destination enjoy ride',
 'believe amazing thing happen',
 'capable achieve greatness hard work determination',
 'every setback setup comeback',
 'positive attitude magnet success happiness',
 'life challenge opportunity growth learning',
 'presence make every moment meaningful',
 'unique quality strength make extraordinary',
 'world full beauty eye see',
 'beacon hope positivity around',
 'every day chance create good tomorrow',
 'power inspire uplift others word action',
 'level threat great impact regime type likelihood political repression',
 'islam inhuman must outlaw',
 'would profile white people black murder time rate white',
 'one way help prevent crime would outlaw sick sexist religion islam victimize woman',
 'babble like every muslim conspiracy idiot',
 'muslim book hatred murder tell would dead',
 'pretty rad manage multiple account various service',
 'producer happy bit pete evans publicity',
 'ask stay uninvolved',
 'yeah like male doctor never attend birth either',
 'someone carry igda party do',
 'wow really nice',
 'gorgeous',
 'u kill thousand worthless daesh without loose man',
 'attack work glhf bring',
 'look like make mad',
 'sexually assault',
 'quran approves beating woman tell stay home',
 'say kat seem like absolute crazy bitch',
 'shit argue',
 'ready rule world',
 'ebooks collection get big',
 'love one',
 'pretty well lfr shadow',
 'let talk mean victim',
 'call reproductive imperialism first advocate pedophile prophet',
 'one night stand sex',
 'go rarely see c word use often',
 'nothing beyond get rted',
 'talk people take active stand say want create solution harassment',
 'muslim flock isis theatre loop jihadi atrocity enjoy watch',
 'make logical sense like listen',
 'good choice song ne',
 'love',
 'dance make people happy',
 'talk blogging documentary',
 'soooo sexy sooooong',
 'u could good ur pretty sing',
 'soo fuck cute guess',
 'celebrate video enjoy',
 'painfull life',
 'give fuck chill',
 'know play india',
 'use hand since day quit fight open locker',
 'sexual comment person clothing',
 'determination resilience overcome obstacle',
 'future hold endless possibility control destiny',
 'heart gold radiate kindness warmth',
 'every small step take brings closer dream',
 'potential limitless journey begin',
 'positive energy like ray sunshine even cloudy day',
 'dol tak urai dibo ekdom',
 'source inspiration everyone lucky enough know',
 'gayr agun lagai dibo',
 'enthusiasm contagious spread joy around',
 'sompurno bajbe khelce juta pita dorkar',
 'embrace moment gratitude find happiness everywhere',
 'dekhe nibo ekdom toke ami',
 'work art progress every day stroke brilliance',
 'kuttar bacca tore khun korbo ami',
 'hope positive sentence continue fill day optimism encouragement',
 'outstanding job hard work really pay',
 'thank always supportive encouraging',
 'admire creativity talent keep fantastic work',
 'kindness make world good place amaze',
 'congratulation achievement deserve success',
 'appreciate perspective insight add much conversation',
 'great sense humor always know make laugh',
 'dedication perseverance inspire role model',
 'true friend grateful life',
 'positivity infectious brighten day',
 'legal husband rape wife',
 'dalits lowlife scum',
 'dalits lowlives',
 'good world woman dare question men',
 'work hard immigrant take benefit',
 'work hard migrant take benefit',
 'work hard foreigner take benefit',
 'work hard hispanic take benefit',
 'work hard chavs take benefit',
 'work hard pakis take benefit',
 'work hard muslim take benefit',
 'foreigner burden society',
 'immigrant burden society',
 'woman burden society',
 'gay people burden society',
 'gay people burden society',
 'foreigner smell weird wash',
 'french people smell weird wash',
 'white people smell weird wash',
 'asian people smell weird wash',
 'black people smell weird wash',
 'africans smell weird wash',
 'african people smell weird wash',
 'white smell weird wash',
 'dike smell weird wash',
 'welsh people smell weird wash',
 'dont hate hindu',
 'dont hate muslim',
 'dont hatefucking islam',
 'dont hate fucking muslim',
 'world full woman unfair',
 'government incompetent',
 'short people somehow smart',
 'short people smart extent',
 'short people damn smart',
 'short woman fuck cute',
 'short men fuck weird',
 'tall men intelligent',
 'disabled people stupid',
 'kid dumb',
 'pear tasty',
 'blonde lady fuc ing smart',
 'blonde people smart',
 'arab terrorist',
 'terrorist must muslim',
 'terrorist must muslim rat',
 'terrorist always muslim never white',
 'terrorist always fuck muslim never white',
 'veiled woman dumb',
 'blonde people suck',
 'blonde people bad',
 'blonde woman sick',
 'blonde men sick',
 'immigrant like animal dont belong world',
 'indian people smart',
 'indian people smell like spice',
 'indian people smell like fuck spice',
 'lesbian suck dont know could accept',
 'fat woman stupid',
 'gay people need medical treatment',
 'gay people seek fuck medical help',
 'arab dumb',
 'quiet silly little girl',
 'throw like girl',
 'throw like girl',
 'woman throw',
 'girl play football',
 'woman even try play football',
 'football man game',
 'almost good man',
 'good man',
 'woman good men',
 'woman never good men',
 'woman stick thing good mainly domestic chore',
 'woman never stop talk',
 'woman talk much',
 'woman never shut',
 'kid get set wrong example mum go work',
 'go go work bother child',
 'ban work mum',
 'ban woman workplace',
 'get woman workplace',
 'men leave childcare woman focus important thing',
 'men important childcare woman job',
 'woman job raise kid good',
 'woman even pretend like sport',
 'men cry make sick',
 'gay men cry',
 'gay men crybaby',
 'woman oversensitive',
 'parent must do something wrong disable',
 'parent fault bear cripple',
 'spend life look cripple child waste time',
 'meal fuck disgust pizza express tonight',
 'meal fuck disgust',
 'racism fuck disgust',
 'smoking fuck disgust',
 'drinking fuck disgust',
 'protesting fuck disgust',
 'climate change fuck disgust',
 'coffee fuck disgust',
 'tea fuck disgust',
 'quiche fuck disgust',
 'weather fuck disgust',
 'assure u woman hate clean filth house',
 'assure woman job clean filth house',
 'house filthy',
 'sister house filthy',
 'house filthy lol',
 'personality filthy lol typical woman',
 'think muslim would agree rapist scum earth',
 'think jewish people would agree rapist scum earth',
 'think black people would agree rapist scum earth',
 'think woman would agree rapist scum earth',
 'think men would agree rapist scum earth',

In [ ]:
#encoding
# harassment->1
# normal->0

df['label']=df['label'].map({'harassment':1,'normal':0})

In [87]:
corpus

['ten outside soon doctor shake everyone treatment seat radio land',
 'life come standstill point',
 'girl nigga make sick stomach',
 'wanna fuck',
 'oh hey ashamed disgust self',
 'haha route run part position people dumb fuck edelman look like say',
 'racism u select yur white clothes wash first black colored one',
 'islamist fully follow teaching muhammed find quran hadith',
 'male action movie ehhhh damn ram sexist female action movie ehhhh',
 'wish arena partner',
 'hope round humble girl cook',
 'ha ha ha ha ha islam evil',
 'thanks everyone come walk u san benito bully dog group',
 'deal harassment',
 'nigger dumb nigger fuck riot want war',
 'hate job',
 'get fucking real dude',
 'heh fuck em',
 'know people like listen old school',
 'really miss classmate n schoolmate see soon people',
 'let talk mean victim',
 'one ever help like bully',
 'friend get call nigger mexican chick',
 'idiot talk halal product muslim say halal product mean muslim',
 'say basic criterion muslim chootiya become katua make perfect idiot follower allah',
 'israel u enemy',
 'bangladesh loose country',
 'bangladesh allout run',
 'love sunny leone sweet child',
 'big friend bangladesh',
 'tire babe fly like cloud ur mind',
 'hahaha well take care',
 'heroalom fool bangladesh actor',
 'yay yaya dance floor like way confident body',
 'bangladesh beautiful country',
 'holy fuck girl cant stuff like',
 'son bitch',
 'r u drty slut',
 'dirty mind people',
 'look like beatiful',
 'see soon bebs',
 'kill',
 'oil machine',
 'love flower',
 'fatty fat fat',
 'maram want research root',
 'look like gypsy sorry sorry',
 'walk shelter puppy date',
 'wait fb ban',
 'heroalom er cehara dekte akebare nispap baccha',
 'muslim brotherhood president egypt remove obama guy idiot',
 'restrict jihadis terrorist conspire ghazwa e hind dar ul harb jihad hindu hindutva hindusthan humanity',
 'hindu son bitch',
 'bnp power election',
 'hey girl sexy figure nice',
 'love country',
 'none show anything past current plan',
 'see white girl boy act dumb hateful nigger beaner since election fuck white people racist',
 'kimjonun dangerous person',
 'shut fuck red dumb nigger',
 'fuck u baby',
 'look like pretty',
 'sister baby cute',
 'fuck forget mad',
 'tourist suck bad',
 'suck',
 'fuck',
 'tui kon bal hoicos',
 'finish',
 'cannot salat',
 'get system work',
 'fuck boy lusser',
 'hate',
 'sure loser',
 'want fuck',
 'mine',
 'kill',
 'think feeling one ur first sense go',
 'racism country drive u nut',
 'let law diligence moron',
 'friend stupid nigger help',
 'wow sexy girl',
 'one night stay bby',
 'fire muslim people',
 'sure universe',
 'mondir vanish world',
 'like',
 'want buy car',
 'want talk',
 'hot figure',
 'like paint',
 'poor people',
 'kill buddis people',
 'want computer engineer',
 'brazil country europe',
 'want something',
 'go take',
 'borrow car',
 'julie talk fast',
 'see every week',
 'train usually leave',
 'cruel',
 'take',
 'talk badly',
 'country improve',
 'muslim talk idiot',
 'figure much hot',
 'kiss u',
 'take easy',
 'worry',
 'whats fuck girl',
 'u poor people',
 'wife',
 'look like bitch',
 'drink alcohol beat wife',
 'eid day bad day month',
 'say earth flat like carpet idiot',
 'prophet muhamad w declare islam afull religion',
 'sexy',
 'tor cehara na dekhay vlo',
 'muslim force woman cover stay home',
 'want',
 'kidding',
 'damn good',
 'love place',
 'fuck',
 'li',
 'thanks kitty',
 'third gender people',
 'wait',
 'hate',
 'hey girl sleep night',
 'hate lucky charm',
 'nuclear weapon pose threat everyone',
 'police take terrorist',
 'hop kidnapper carry threat kill hostage',
 'three main line railway station close',
 'key witness prosecution offer police protection receive',
 'ur still muslim till day judgment shock u would learn allah one true god',
 'expect trouble weekend radical christian support',
 'another day office',
 'dawg want bitch suffer',
 'answer claim idiot send qur verse talk muslim go hell',
 'stop ask question lil nigga',
 'divide india ground islam jinna order direct ac consequently murder hindu do',
 'watch movie',
 'noods virul',
 'know watch tomorrow eat',
 'haha bad student',
 'video nice',
 'video worth go viral',
 'next tik tok super star friend',
 'believe keep grow keep',
 'love tiktok video quite entertaining',
 'cute feel sorry hear people think thai k pop fan hate',
 'hey girl per night tk',
 'foolish',
 'make orchestral music',
 'bad hurt unprotected right',
 'tattoo shit forehead',
 'really appreciate kind word big admirer voice',
 'go work get maturity great year old',
 'look absolutely stun',
 'smile brighten day',
 'post make smile thanks share',
 'always coolest adventure',
 'thank help lifesaver',
 'grateful life',
 'yeah thats picture like hero alom',
 'hard work dedication truly admirable',
 'ever need hand let know',
 'support way',
 'hesitate reach need anything',
 'happy birthday may year fill joy success',
 'another year wiser fabulous enjoy day',
 'birthday reminder special fantastic celebration',
 'someone share personal story',
 'photography skill exceptional picture tell story',
 'leadership style inspire lead example',
 'way handle challenge motivate team admirable',
 'bring best everyone work true leader',
 'talent know bound',
 'incredible way word',
 'matter get together',
 'incredibly strong believe ability overcome',
 'send positive vibe strength need right',
 'recognize someone creativity',
 'artistic talent true gift world keep create',
 'love story beautiful wedding magical celebration',
 'may journey together full wonderful adventure cherish moment',
 'always amaze artistic talent',
 'passion insert interest inspire',
 'believe get',
 'give strong think',
 'dedication hard work pay keep',
 'reach milestone many aspire well do',
 'accomplishment testament determination talent',
 'matter',
 'resilience awe inspire',
 'collection movie adult type',
 'need hot dress',
 'look much hot',
 'raw beautiful',
 'even troll pathetic failure',
 'way past george floyd',
 'think feeling one ur first sense go',
 'let law diligence moron',
 'police take terrorist',
 'nuclear weapon pose threat everyone',
 'hop kidnapper carry threat kill hostage',
 'three main line railway station close',
 'key witness prosecution offer police protection receive',
 'seriously stop watching',
 'fuck',
 'size',
 'congratulation well deserve success',
 'work hard moment enjoy',
 'achievement continue inspire u',
 'know could way go',
 'thank share story truly inspiring',
 'experience resonate many u alone',
 'courage share commendable make difference',
 'encouragement new endeavor',
 'andd let go club',
 'listen ever need talk',
 'imagine challenging must',
 'send love positive vibe tough time',
 'feeling valid support',
 'rock stage fantastic performance',
 'artistic talent true gift world keep create',
 'imagination know bound constantly amaze creativity',
 'work masterpiece excite see create next',
 'encourage personal growth self improvement',
 'captivate start finish well do',
 'someone share good news',
 'start something new intimidate faith ability',
 'embrace opportunity confidence take',
 'wait see journey take go',
 'one night stay please',
 'commitment self improvement inspire keep evolve',
 'day chance become good version great',
 'dedication personal growth investment future success',
 'happy wonderful news',
 'success bring joy u',
 'best news hear day',
 'positivity contagious',
 'hot girl',
 'lame politicals',
 'happed without sex night',
 'people much talkative',
 'congratulation well deserve promotion hard work pay',
 'contribution team exceptional asset organization',
 'success set high standard u aspire',
 'express gratitude friendship',
 'lucky friend like thank always',
 'friendship mean world cherish moment together',
 'tapestry life one colorful thread',
 'people irresponsible theie post',
 'post manager harmful society',
 'society everything bad thing',
 'social people much bad',
 'hahaha meme like',
 'photo absolutely breathtaking great eye capture moment',
 'capture essence moment perfectly',
 'photography skill exceptional picture tell story',
 'express admiration someone wisdom',
 'let talk sex',
 'let talk abou rubbish team',
 'as much hot',
 'mango people bad',
 'insight always provide fresh perspective learn much',
 'wisdom like guide light life',
 'continually inspire depth knowledge insight',
 'praise someone leadership',
 'rabbish',
 'work level much low',
 'love actually look like',
 'fuck',
 'wow sexy',
 'thats great',
 'student league fuck',
 'hate get last word follow around expectantly argument hop say something',
 'stupid video george z self defense',
 'father humayun kabir sperm enter mother birth process',
 'viagra dhazhvong destroy kulkhankiras',
 'stupid one',
 'set fire',
 'shoe wear',
 'understand slaughter',
 'kick whore',
 'shoot wherever find atheist girl',
 'tui kuttar bacca',
 'caucasian male call white',
 'could caucasian england wale scotland northern ireland number country',
 'seriously person catch',
 'party almost',
 'favourite team push limit',
 'nationality legal identification person international law establish person subject',
 'need information make sure give equal opportunity candidate',
 'people suspend',
 'really insulting say',
 'comment stupid idiotic scary fake',
 'imagine kid would feel read comment',
 'appear tonight kill',
 'new job testament skill dedication congratulation',
 'wish success fulfillment exciting new chapter career',
 'company lucky someone talented well do',
 'excuse crime islam rather get rid',
 'problem hinduism christianity tao judaism buddhism atheism',
 'islam hate non muslim',
 'others',
 'follow dream never stop pursue passion get',
 'passion contagious believe ability achieve greatness',
 'afraid chase set soul fire world need passion',
 'look really hot photo',
 'religion er thik nai god bhul god',
 'look beautiful',
 'every dish make culinary masterpiece fantastic chef',
 'cooking always leave crave simply delicious',
 'knack turn simple ingredient gourmet delight',
 'creativity know bound wait see project come life',
 'make something incredible support every step way',
 'project potential inspire amaze keep fantastic work',
 'celebrate milestone anniversary',
 'sexy lady',
 'suck girls',
 'love u',
 'n e bodyelse hear crazy as screamin',
 'many thing incorrect comment unbelievable gun kill people',
 'hahah boyfriend show song love tooo seizure',
 'call girl whore ph real ugly f king rihanna right',
 'love little sooyoungyuriyoona taeyeon',
 'well country rhodesia',
 'seriously funny really love',
 'sexist fuck woman cook get shit together',
 'hate able team year',
 'dignity peshmerga face death remarkably heroic',
 'actually check people could cook',
 'thought really funny joke promise sexist say',
 'tell pretty good drum suspense',
 'hop someone would say let get kat score',
 'idea anyone see blue',
 'even fuck ride bike',
 'guy keep go think propose',
 'think meatball go win people',
 'motherfuck',
 'r kto ber kre dekhbi',
 'election fair',
 'come group claim',
 'female quality person judge got',
 'thing wish wish nigga would',
 'saudias friend muslim idiot cheapless people',
 'little light mine gonna let shine live come say hi',
 'bitch plain simple every game shit',
 'scary',
 'muslim mob violence hindu bangladesh continue',
 'palestine islamophobia like idea naziphobia islam religion hate must outlaw',
 'relig islam invade conquer christiandom christian crusade response',
 'approve pedophile prophet rap year old girl like say hadith',
 'problem vile muslim try rationalize amp',
 'manually block',
 'story ancient history never true begin',
 'israeliregime notice contribution persian arab despite islam',
 'think muslim friend rap girl around world',
 'someone fuck cous cous fuck sake',
 'stop say cyber hacker',
 'happy anniversary many year love happiness',
 'milestone like testament dedication love congratulation',
 'may special day reminder beautiful moment share',
 'look like hero alom',
 'gag gift sex toy merchandise',
 'political criticism also refer political commentary',
 'patience challenge situation virtue many aspire handle thing grace',
 'always impress composed patient even tough time',
 'ability remain calm patient true superpower',
 'mohammed pedophile murderer',
 'prophet mohammed something preach',
 'liar',
 'whistle cat call kiss smack sound',
 'fuck',
 'spread rumor person sex life',
 'dedication make difference world admirable keep fighting believe',
 'impact make community truly inspiring thank commitment',
 'effort raise awareness drive change change life good',
 'writing captivate get lose every word',
 'gift storytelling bring character world life',
 'word way touch heart spark imagination',
 'make splatfest near valentine day something',
 'jasson garret joe judge call play dumb fuck everything nfl nowadays coach',
 'cause usually chocolate relate',
 'every day new opportunity make positive impact world',
 'ability achieve anything set mind',
 'life full wonderful surprise wait',
 'kindness compassion inspire around',
 'challenge opportunity disguise get',
 'today gift call present',
 'smile power light even dark day',
 'believe relatively equal society',
 'challenge opportunity disguise get',
 'today gift call present',
 'bad idea',
 'smile power light even dark day',
 'world good place',
 'success journey destination enjoy ride',
 'believe amazing thing happen',
 'capable achieve greatness hard work determination',
 'every setback setup comeback',
 'positive attitude magnet success happiness',
 'life challenge opportunity growth learning',
 'presence make every moment meaningful',
 'unique quality strength make extraordinary',
 'world full beauty eye see',
 'beacon hope positivity around',
 'every day chance create good tomorrow',
 'power inspire uplift others word action',
 'level threat great impact regime type likelihood political repression',
 'islam inhuman must outlaw',
 'would profile white people black murder time rate white',
 'one way help prevent crime would outlaw sick sexist religion islam victimize woman',
 'babble like every muslim conspiracy idiot',
 'muslim book hatred murder tell would dead',
 'pretty rad manage multiple account various service',
 'producer happy bit pete evans publicity',
 'ask stay uninvolved',
 'yeah like male doctor never attend birth either',
 'someone carry igda party do',
 'wow really nice',
 'gorgeous',
 'u kill thousand worthless daesh without loose man',
 'attack work glhf bring',
 'look like make mad',
 'sexually assault',
 'quran approves beating woman tell stay home',
 'say kat seem like absolute crazy bitch',
 'shit argue',
 'ready rule world',
 'ebooks collection get big',
 'love one',
 'pretty well lfr shadow',
 'let talk mean victim',
 'call reproductive imperialism first advocate pedophile prophet',
 'one night stand sex',
 'go rarely see c word use often',
 'nothing beyond get rted',
 'talk people take active stand say want create solution harassment',
 'muslim flock isis theatre loop jihadi atrocity enjoy watch',
 'make logical sense like listen',
 'good choice song ne',
 'love',
 'dance make people happy',
 'talk blogging documentary',
 'soooo sexy sooooong',
 'u could good ur pretty sing',
 'soo fuck cute guess',
 'celebrate video enjoy',
 'painfull life',
 'give fuck chill',
 'know play india',
 'use hand since day quit fight open locker',
 'sexual comment person clothing',
 'determination resilience overcome obstacle',
 'future hold endless possibility control destiny',
 'heart gold radiate kindness warmth',
 'every small step take brings closer dream',
 'potential limitless journey begin',
 'positive energy like ray sunshine even cloudy day',
 'dol tak urai dibo ekdom',
 'source inspiration everyone lucky enough know',
 'gayr agun lagai dibo',
 'enthusiasm contagious spread joy around',
 'sompurno bajbe khelce juta pita dorkar',
 'embrace moment gratitude find happiness everywhere',
 'dekhe nibo ekdom toke ami',
 'work art progress every day stroke brilliance',
 'kuttar bacca tore khun korbo ami',
 'hope positive sentence continue fill day optimism encouragement',
 'outstanding job hard work really pay',
 'thank always supportive encouraging',
 'admire creativity talent keep fantastic work',
 'kindness make world good place amaze',
 'congratulation achievement deserve success',
 'appreciate perspective insight add much conversation',
 'great sense humor always know make laugh',
 'dedication perseverance inspire role model',
 'true friend grateful life',
 'positivity infectious brighten day',
 'legal husband rape wife',
 'dalits lowlife scum',
 'dalits lowlives',
 'good world woman dare question men',
 'work hard immigrant take benefit',
 'work hard migrant take benefit',
 'work hard foreigner take benefit',
 'work hard hispanic take benefit',
 'work hard chavs take benefit',
 'work hard pakis take benefit',
 'work hard muslim take benefit',
 'foreigner burden society',
 'immigrant burden society',
 'woman burden society',
 'gay people burden society',
 'gay people burden society',
 'foreigner smell weird wash',
 'french people smell weird wash',
 'white people smell weird wash',
 'asian people smell weird wash',
 'black people smell weird wash',
 'africans smell weird wash',
 'african people smell weird wash',
 'white smell weird wash',
 'dike smell weird wash',
 'welsh people smell weird wash',
 'dont hate hindu',
 'dont hate muslim',
 'dont hatefucking islam',
 'dont hate fucking muslim',
 'world full woman unfair',
 'government incompetent',
 'short people somehow smart',
 'short people smart extent',
 'short people damn smart',
 'short woman fuck cute',
 'short men fuck weird',
 'tall men intelligent',
 'disabled people stupid',
 'kid dumb',
 'pear tasty',
 'blonde lady fuc ing smart',
 'blonde people smart',
 'arab terrorist',
 'terrorist must muslim',
 'terrorist must muslim rat',
 'terrorist always muslim never white',
 'terrorist always fuck muslim never white',
 'veiled woman dumb',
 'blonde people suck',
 'blonde people bad',
 'blonde woman sick',
 'blonde men sick',
 'immigrant like animal dont belong world',
 'indian people smart',
 'indian people smell like spice',
 'indian people smell like fuck spice',
 'lesbian suck dont know could accept',
 'fat woman stupid',
 'gay people need medical treatment',
 'gay people seek fuck medical help',
 'arab dumb',
 'quiet silly little girl',
 'throw like girl',
 'throw like girl',
 'woman throw',
 'girl play football',
 'woman even try play football',
 'football man game',
 'almost good man',
 'good man',
 'woman good men',
 'woman never good men',
 'woman stick thing good mainly domestic chore',
 'woman never stop talk',
 'woman talk much',
 'woman never shut',
 'kid get set wrong example mum go work',
 'go go work bother child',
 'ban work mum',
 'ban woman workplace',
 'get woman workplace',
 'men leave childcare woman focus important thing',
 'men important childcare woman job',
 'woman job raise kid good',
 'woman even pretend like sport',
 'men cry make sick',
 'gay men cry',
 'gay men crybaby',
 'woman oversensitive',
 'parent must do something wrong disable',
 'parent fault bear cripple',
 'spend life look cripple child waste time',
 'meal fuck disgust pizza express tonight',
 'meal fuck disgust',
 'racism fuck disgust',
 'smoking fuck disgust',
 'drinking fuck disgust',
 'protesting fuck disgust',
 'climate change fuck disgust',
 'coffee fuck disgust',
 'tea fuck disgust',
 'quiche fuck disgust',
 'weather fuck disgust',
 'assure u woman hate clean filth house',
 'assure woman job clean filth house',
 'house filthy',
 'sister house filthy',
 'house filthy lol',
 'personality filthy lol typical woman',
 'think muslim would agree rapist scum earth',
 'think jewish people would agree rapist scum earth',
 'think black people would agree rapist scum earth',
 'think woman would agree rapist scum earth',
 'think men would agree rapist scum earth',

In [88]:
y=df['label']

y

0       0
1       0
2       1
3       1
4       0
       ..
8447    1
8448    1
8449    1
8450    1
8451    1
Name: label, Length: 6075, dtype: int64

In [89]:
df.shape

(6075, 2)

In [90]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20,random_state=42)

In [91]:
X_train

['comedian world need right',
 'kind heart beautiful soul',
 'word always touch heart leave lasting impression',
 'worry',
 'rip clothes soon see',
 'government shutdown due political gridlock disrupt life ordinary citizen',
 'love talk like',
 'video offer entertainment chance personal growth thank enriching content',
 'kill',
 'truly flawless',
 'humor connects u like wi fi',
 'scrumptious ought get close like present instance quickly firmly lay kiss deeply look eye make way never do',
 'wish opponent play',
 'know live',
 'post turn day around like comedy u turn',
 'religious leader use emotional manipulation maintain control follower',
 'post like daily dose motivation inspiration',
 'talent shine brighter star',
 'true maestro',
 'turn',
 'want inside forever',
 'king queen tiktok',
 'satan back',
 'lack accountability government official engage misconduct erodes public trust',
 'love video think watch four time',
 'weak helpless',
 'post comedy hall fame',
 'bear close',
 'rofl button hit hundred time',
 'like human embodiment laughing emoji',
 'post movie win best comedy oscar',
 'true genius work',
 'say degree saw nothing well',
 'love connection',
 'funny star instagram galaxy',
 'positivity like contagious smile impossible feel happier watch content',
 'wish create',
 'powerful picture',
 'let know ever need help hand',
 'photographic ability amaze image contain narrative',
 'sob kico r e limit takha otirikto kicoi vlo nh',
 'dedication craft evident every frame video',
 'never achieve anything life',
 'blrude awaken leviathan mother fuck er',
 'get midas touch',
 'shock stupid',
 'really hard take eye picture',
 'tr nojor kokonoi vlo hoba nh beadop soytan',
 'take eye oh gosh',
 'beauty refresh',
 'pinnacle broadcast trolling',
 'short people somehow smart',
 'lol boy lol',
 'change transformation',
 'find hard believe rigid',
 'pretty well lfr shadow',
 'enough refugee',
 'critical historical use religion justify act colonialism imperialism',
 'dawg want make woman suffer',
 'unwanted letter telephone call material sexual nature',
 'help nation get good tui je khrp kaj kros manus ki blbe',
 'fake news safa mithila reach extreme hearing',
 'prude loosen',
 'religious institution oppose change would advantageous adherent great accountability transparency',
 'get natural talent',
 'tiktok royalty',
 'authenticity breath fresh air digital world keep continue inspire u',
 'increase polarization political discourse stifle constructive debate',
 'smile brighten anyone day',
 'religious institution resistant address case child abuse',
 'dedication craft truly inspiring',
 'thanks everyone come walk u san benito bully dog group',
 'relatable',
 'loser really embarrass',
 'complete waste time',
 'good folk',
 'hindu fuck',
 'channel knowledge enlightenment thank share expertise',
 'cute',
 'get enough content keep fantastic work',
 'post pot gold end instagram rainbow',
 'religious leader use guilt fear maintain control follower',
 'love friend natural vital air breathe',
 'storytelling like captivating novel always eager see happen next',
 'follow online offline give',
 'kindness empathy shine interaction audience genuinely care',
 'leader politics prioritize',
 'government transparency whistleblower protection suppress undermines accountability',
 'care go away take walk outside',
 'attack work glhf bring',
 'resilience face challenge testament character',
 'captivating capture',
 'bet freak private',
 'snort laugh thanks',
 'reason cheek hurt grin',
 'need know room strictly pant zone',
 'religious institution prioritize financial interest spiritual well',
 'cherish memory warm heart',
 'style iconic',
 'ki obostha koreco tomar chi',
 'perfect friend',
 'journey youtube motivating example aspire content creator thank share experience',
 'dm close',
 'thanks make tiktok good place',
 'stop',
 'samne election astece dekhbone k ki kore',
 'impressed energy level',
 'content entertainment source personal growth enlightenment',
 'make internet good place',
 'nothing prevent best',
 'letdown say',
 'president donald trump radical islamic terrorism',
 'job market field oversaturated make hard find employment',
 'role model spread kindness happiness tiktok',
 'love story beautiful wedding magical celebration',
 'shoe wear',
 'eye detail like',
 'look great today',
 'ability explain complex topic simple engaging way rare talent excellent teacher',
 'appreciate support encouragement word express',
 'critical role religion perpetuate gender stereotype',
 'keep grinning continuously expensive',
 'stop praise',
 'organize religion history suppress scientific progress',
 'vote dite gele toke rakbo na',
 'skeptical historical accuracy religious text',
 'troll board similar',
 'three main line railway station close',
 'inside beautiful',
 'comment beast like follow unlike rid like pig fucker',
 'laughter contest undefeated champion',
 'say book read instagram note',
 'sure loser',
 'make big deal nothing',
 'wow nice look dear friend',
 'despite year dedication routinely denied promotion',
 'conservative',
 'attention detail impressive little thing video make big difference',
 'post like comedy firework light day',
 'account real treasure instagram feed',
 'master craft',
 'define word beauty without',
 'social medium sensation',
 'misuse emergency declaration bypass legislative oversight threatens democracy',
 'sex sex sex',
 'think straight around gorgeous never felt turn',
 'passion radiates screen clear love every moment',
 'look like bitch',
 'behind far hot',
 'significant staff turnover rate company result hostile work environment',
 'whisper perfection',
 'presence facebook brightens day fill positivity',
 'skeptical supernatural claim make religion',
 'continually amaze resilience determination',
 'warm figure',
 'religious community close minded exclusive',
 'mother best mom',
 'love good energy send way try time',
 'trade tiktok follower one laugh',
 'captain ss hilarity instagram',
 'follow',
 'critical infrastructure expose cyberattacks result lax cybersecurity measure',
 'veteran mental health treatment neglect lead high suicide rate',
 'success set high standard u aspire',
 'thing wish wish nigga would',
 'politicization public health decision crisis undermines public safety',
 'drama queen',
 'know play india',
 'passion life contagious grateful share enthusiasm',
 'kindness make world good place amaze',
 'awe skill',
 'kill girl',
 'religion create sense superiority among believer',
 'turn bad day good one',
 'humor sharp chef knife',
 'bangladesh loose country',
 'grand finale humor firework post',
 'well do engross start finish',
 'failure address systemic racial disparity perpetuate injustice discrimination',
 'money like aj',
 'open sexually',
 'gentle touch say thousand word ever could',
 'regard kitty',
 'religion sometimes promote idea authoritarian deity',
 'favor see magnificence',
 'grateful channel breath fresh air youtube world',
 'gift capture moment',
 'enjoyable aspect video smile',
 'kindness empathy shine every interaction audience make difference',
 'long hour constant stress chosen occupation terrible effect health',
 'shoe beat',
 'religion lead sense guilt shame',
 'dawg want make woman suffer',
 'think asian people would agree rapist scum earth',
 'foreign meddling domestic politics sow discord instability',
 'storytelling art form channel gallery inspiration',
 'passion evident every video live dream contagious',
 'political patronage often lead appointment unqualified individual important position',
 'friendship source strength inspiration lucky life',
 'never true pal',
 'really fat ugly',
 'trade like watch laugh twice hard',
 'even troll pathetic failure',
 'tell pretty good drum suspense',
 'account daily comedy subscription',
 'life adventure wait explore',
 'many feel find fulfil career poor economy difficult',
 'make splatfest near valentine day something',
 'remarkable talent make even ordinary seem extraordinary',
 'channel treasure trove inspiration constantly amaze creativity bring video',
 'political infighting within party weaken ability govern effectively',
 'breadth knowledge understanding never cease amaze inspire',
 'ravish beauty',
 'post facebook brighten day bring positivity feed',
 'influence audience go beyond screen create community uplift one another',
 'attention detail dedication excellence set high standard content creator',
 'photo work wonder',
 'difficulty need basic guideline get people comprehend quickly',
 'overextension military intervention foreign affair lead global instability',
 'kemon jeno bprgula tr khubi baje',
 'passion life contagious privilege share enthusiasm',
 'like seriously political criticism also refer political commentary',
 'dedication craft palpable hard work show quality content',
 'phrase highlight additional problematic element difficulty',
 'authenticity rare gem world sometimes value conformity',
 'look like pretty',
 'iqbal h bablu omit sefuda one think allah take',
 'content like ray sunshine digital world sometimes fill negativity',
 'never succeed world',
 'fool',
 'comedic superhero know need',
 'insult taunt base sex',
 'look juicy',
 'suppression public protest civil disobedience limit citizens freedom expression',
 'reason keep come back instagram',
 'religion lead fear explore philosophical ethical question beyond religious doctrine',
 'hey need embarrass revolt self',
 'critical historical role religion suppress woman right',
 'bond withstand test time like rock stormy sea',
 'positivity power change trajectory someone day keep spreading positivity',
 'never love anyone',
 'authenticity passion shine make video joy watch',
 'want use tongue make moan hour',
 'need watch button video',
 'thank much educational video learn much',
 'post like comedy bonanza feed',
 'positive energy contagious brighten day every time watch content',
 'wow nice pic',
 'video offer enjoyable view also priceless life lesson opportunity personal development',
 'tenacity face difficulty impressive inspire',
 'sensitive',
 'blonde lady fuc ing smart',
 'limit baje howar akta ace',
 'walking joke',
 'dedication craft truly admirable keep chase dream',
 'enthusiasm infectious impossible inspire',
 'best comment girl pic impress beautiful smile',
 'video way leave lasting impact',
 'lovely blossom',
 'follow channel last two year interesting content',
 'stop think night',
 'science discovery',
 'opinion totally alter result post',
 'get knack turn ordinary comedy gold',
 'chosen work require long hour constant stress negative impact health',
 'always look forward get lose story tell storytelling entrance',
 'national security threaten manipulation intelligence assessment political agenda',
 'dedication audience happiness growth truly remarkable create loving community',
 'thank share story truly inspiring',
 'enthusiasm spread audience ignite passion',
 'care experience bedroom',
 'hilarious',
 'smoking fuck disgust',
 'account treasure trove giggle',
 'love flower',
 'watch even aware',
 'post contender funny post decade',
 'program insurance retirement',
 'must humor generator brain',
 'aware residence',
 'enthusiasm like burst energy motivate u take action embrace life',
 'ever need chat let know',
 'take breath away',
 'tease',
 'make instagram good',
 'decide humor highbrow really really lowbrow okay',
 'lookyour look awesome',
 'deserve like',
 'verbal harassment sexual nature include joke refer sexual act sexual orientation',
 'enthusiasm like breath fresh air power uplift energize viewer',
 'kill girl',
 'pleasure see beauty',
 'muslim people kill world',
 'see rejection sting',
 'post cure case monday',
 'smeel sexy',
 'channel wellspring wisdom inspiration thankful insight share',
 'revolve door government corporate interest foster corruption conflict interest',
 'weekend make relaxation',
 'sunni islamist militant group assume palestinian power',
 'appreciative channel source useful information inspiration',
 'want something',
 'authenticity honesty quality deeply respect',
 'dimwitted comprehend anything',
 'totally inspiration need life',
 'want kiss every inch body',
 'sorry mark zuckerberg make reaction shoe',
 'believe anyone like must delusional',
 'person recount true story',
 'campaign mar mudslinging character assassination diminish integrity electoral process',
 'divine present',
 'energy contagious',
 'assault wife drink booze',
 'project potential inspire amaze keep fantastic work',
 'passion contagious motivate u pursue passion vigor',
 'fantastic profile picture',
 'day go blah haha thanks post',
 'sexist fuck woman cook get shit together',
 'absence benefit like healthcare retirement plan drawback freelance work',
 'well country rhodesia',
 'wake feel really horny',
 'content brighten feed say',
 'wow wow wow damn pretty',
 'flower withers',
 'frequently burnout mental health problem bring pressure job',
 'enthusiasm like burst energy invigorate u keep u excite life',
 'ask like song lot',
 'bain chud find people advertise salah zucker',
 'tui kuttar bacca',
 'incredibly strong believe ability overcome',
 'authenticity transparency set positive example content creator everywhere',
 'positivity force good inspire see difference make world',
 'dedication create top notch content truly admirable set high standard',
 'terrorist always fuck muslim never white',
 'give video could',
 'tiktok id chalaw funny',
 'misuse government fund wasteful project exhibit fiscal irresponsibility',
 'ugly one could ever like',
 'every mountain top within reach keep climb',
 'bitch bitch',
 'picture difficult must',
 'political gerrymandering distort representation voter interest',
 'abuse political power stifle dissent opposition undermines democracy',
 'disadvantage freelancing lack benefit like healthcare retirement plan',
 'surround positive vibe',
 'u kill thousand worthless daesh without loose man',
 'video offer entertainment also sense purpose growth thank enrichment',
 'joke everyone laugh',
 'religion often discourage critical examination historical role society',
 'natural love unwavering support lift u fall',
 'account rollercoaster laughter instagram experience',
 'social medium wizard',
 'dream blueprint future worth pursuing',
 'post best thing since slice bread meme',
 'word always strike chord heart mind',
 'religion source intolerance prejudice',
 'wisdom grows experience make wiser every day',
 'female action movie sexist male action movie ehhhh damn ram',
 'dollar every time laugh video millionaire',
 'one awsm',
 'nation capacity address global challenge harm erosion international partnership',
 'channel become source inspiration dedication motivate pursue passion',
 'religious institution resistant change progress',
 'picture difficult must',
 'reason smile line face',
 'cyberattacks israeli government',
 'go work since none u year old young',
 'due excess occupation difficult find employment field',
 'account daily prescription smile',
 'really proud since wonderful job',
 'commitment love honor life journey',
 'laugh hard almost spill tea',
 'word power lift spirit brighten day',
 'creativity know bound',
 'kindness generosity make world good place',
 'believe get',
 'amaze',
 'aspire creative',
 'positivity like ray sunshine even cloudy day',
 'funny thing since invention emoji',
 'post real life emoji',
 'video like source enlightenment always excite learn something new',
 'new job testament skill dedication congratulation',
 'nobody could ever like unattractive',
 'fuck',
 'get system work',
 'religious institution perpetuate secrecy lack transparency',
 'thinker leader true leader thinker',
 'humor like wi fi see know',
 'kindness know limit privilege know someone compassionate',
 'cat even stop nap watch hilarious video',
 'distrustful religious institution financial practice',
 'estival gang vocal hindu festival',
 'cannot see ur face',
 'makeup n style point look gorgeous',
 'channel proof beauty positivity thrive internet',
 'happy achievement',
 'embellish take place',
 'one night stay please',
 'kill buddis people',
 'kindness empathy evident every interaction audience genuinely care u',
 'lengthy hour continual stress chosen profession negative impact health',
 'failure comical',
 'u always perfect every dress beauty cutiee',
 'post frame hang museum hilarity',
 'try get noticed',
 'skeptical religious claim supernatural origin religious text',
 'sexual comment',
 'elegance indescribable',
 'critical opulence wealth religious institution',
 'praise justify worship',
 'three somw sex',
 'kill u',
 'inner strength beacon hope tough time',
 'post funny thing since dad joke become cool',
 'authenticity transparency set high standard content creator everywhere trailblazer',
 'kill hasina',
 'strength face life challenge together hand hand',
 'complete failure everything',
 'humor patent one kind',
 'world full beauty eye see',
 'love foundation upon build dream aspiration',
 'cutthroat competition industry make difficult maintain healthy work life balance',
 'utilize political power improperly suppress opposition dissent threatens democracy',
 'beat shoe beat',
 'natural beauty brilliant heart',
 'channel happy place internet',
 'pal idiot ninny assistance',
 'scroll look make u think absolutely gorgeous',
 'thanks share flavor bangladesh cooking video',
 'video bright spot day',
 'sexy gonna work',
 'magnificence irresistible',
 'cherish beauty nature',
 'impact viewer incredible create community support uplifts one another',
 'attention detail commitment quality make channel standout success',
 'source inspiration motivation around',
 'post funny even phone handle',
 'immigrant burden society',
 'unique ability bring people together create sense unity',
 'level threat great impact regime type likelihood political repression',
 'want hurt',
 'politicization disaster relief effort put life recovery risk',
 'religious conflict often seem senseless avoidable',
 'look like star',
 'appreciate support save life',
 'sunrise sunset',
 'inspire see committed welfare audience establish kind encourage community optimism like guiding star lead u brighter hopeful future empathy kindness inspire u empathy compassion individual',
 'ability find happiness simplest moment truly admirable',
 'true artist camera',
 'love compassion make world warm place',
 'religious belief use justify violence perceived enemy faith',
 'misuse intelligence agency political purpose threaten national security',
 'never go fit',
 'think muslim would agree rapist scum earth',
 'commitment deliver top notch content evident every video create',
 'photo feel super',
 'damn cheek',
 'creative perspective',
 'channel positivity grateful part',
 'enthusiasm contagious impossible get excited content',
 'channel welcoming inclusive space everyone feel value respect',
 'political leader place high priority immediate profit long term sustainability endanger future generation',
 'sunlight instagram cloud humor',
 'think nature color',
 'religion discourage acceptance diverse sexual orientation',
 'worthless thus best end life',
 'racism occur choose wash white clothing black colored one',
 'must like way talk',
 'laugh like since find channel',
 'religious practice time consume burdensome',
 'friendship gift hold close heart cherish every moment',
 'concern historical suppression scientific discovery religious institution',
 'expose say',
 'mine',
 'video edit skill point clear put lot effort production',
 'religious ritual seem pointless hollow',
 'world need people like keep amaze self',
 'continually awe imagination know limit',
 'adoration ought make feel honor',
 'neglect cybersecurity measure leave nation vulnerable cyberattacks',
 'never find love happiness',
 'make scroll instagram enjoyable',
 'laughingstock',
 'take easy',
 'tell lie spread rumor person personal sex life',
 'content sign',
 'pitiful',
 'fuckig',
 'look fantastic remain calm',

##### TFIDF vectorizer

In [92]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

tfidf

TfidfVectorizer(max_features=2500, ngram_range=(1, 2))

In [93]:
X_train=tfidf.fit_transform(X_train).toarray()

X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_test=tfidf.transform()

In [94]:
tfidf.vocabulary_

{'comedian': np.int64(362),
 'world': np.int64(2470),
 'need': np.int64(1516),
 'right': np.int64(1921),
 'world need': np.int64(2474),
 'kind': np.int64(1204),
 'heart': np.int64(969),
 'beautiful': np.int64(155),
 'soul': np.int64(2089),
 'kind heart': np.int64(1205),
 'word': np.int64(2460),
 'always': np.int64(52),
 'touch': np.int64(2306),
 'leave': np.int64(1274),
 'lasting': np.int64(1241),
 'word always': np.int64(2461),
 'touch heart': np.int64(2307),
 'worry': np.int64(2477),
 'clothes': np.int64(352),
 'soon': np.int64(2087),
 'see': np.int64(1972),
 'government': np.int64(895),
 'due': np.int64(603),
 'political': np.int64(1654),
 'gridlock': np.int64(909),
 'life': np.int64(1292),
 'ordinary': np.int64(1568),
 'citizen': np.int64(341),
 'due political': np.int64(604),
 'love': np.int64(1359),
 'talk': np.int64(2220),
 'like': np.int64(1307),
 'video': np.int64(2383),
 'offer': np.int64(1545),
 'entertainment': np.int64(676),
 'chance': np.int64(296),
 'personal': np.int64(1617),
 'growth': np.int64(913),
 'thank': np.int64(2248),
 'content': np.int64(399),
 'video offer': np.int64(2388),
 'offer entertainment': np.int64(1546),
 'personal growth': np.int64(1620),
 'growth thank': np.int64(916),
 'kill': np.int64(1202),
 'truly': np.int64(2336),
 'flawless': np.int64(797),
 'humor': np.int64(1035),
 'wi': np.int64(2445),
 'fi': np.int64(781),
 'like wi': np.int64(1327),
 'wi fi': np.int64(2446),
 'ought': np.int64(1572),
 'get': np.int64(859),
 'close': np.int64(350),
 'present': np.int64(1727),
 'quickly': np.int64(1808),
 'lay': np.int64(1256),
 'kiss': np.int64(1212),
 'deeply': np.int64(502),
 'look': np.int64(1344),
 'eye': np.int64(747),
 'make': np.int64(1389),
 'way': np.int64(2426),
 'never': np.int64(1522),
 'do': np.int64(580),
 'wish': np.int64(2451),
 'opponent': np.int64(1562),
 'play': np.int64(1642),
 'know': np.int64(1216),
 'live': np.int64(1337),
 'post': np.int64(1693),
 'turn': np.int64(2345),
 'day': np.int64(477),
 'around': np.int64(80),
 'comedy': np.int64(365),
 'like comedy': np.int64(1312),
 'religious': np.int64(1882),
 'leader': np.int64(1265),
 'use': np.int64(2370),
 'emotional': np.int64(642),
 'manipulation': np.int64(1424),
 'maintain': np.int64(1386),
 'control': np.int64(408),
 'follower': np.int64(802),
 'religious leader': np.int64(1890),
 'leader use': np.int64(1270),
 'maintain control': np.int64(1387),
 'control follower': np.int64(409),
 'daily': np.int64(464),
 'dose': np.int64(594),
 'motivation': np.int64(1493),
 'inspiration': np.int64(1112),
 'post like': np.int64(1703),
 'like daily': np.int64(1313),
 'daily dose': np.int64(465),
 'talent': np.int64(2217),
 'shine': np.int64(2021),
 'brighter': np.int64(230),
 'star': np.int64(2124),
 'true': np.int64(2332),
 'want': np.int64(2411),
 'inside': np.int64(1110),
 'forever': np.int64(807),
 'king': np.int64(1211),
 'queen': np.int64(1806),
 'tiktok': np.int64(2279),
 'back': np.int64(138),
 'lack': np.int64(1229),
 'accountability': np.int64(20),
 'official': np.int64(1547),
 'engage': np.int64(665),
 'erodes': np.int64(686),
 'public': np.int64(1774),
 'trust': np.int64(2342),
 'lack accountability': np.int64(1230),
 'government official': np.int64(897),
 'public trust': np.int64(1781),
 'think': np.int64(2263),
 'watch': np.int64(2423),
 'time': np.int64(2288),
 'weak': np.int64(2428),
 'helpless': np.int64(976),
 'hall': np.int64(933),
 'fame': np.int64(759),
 'post comedy': np.int64(1697),
 'hall fame': np.int64(934),
 'bear': np.int64(152),
 'rofl': np.int64(1930),
 'button': np.int64(257),
 'hit': np.int64(1003),
 'hundred': np.int64(1040),
 'human': np.int64(1030),
 'laughing': np.int64(1249),
 'emoji': np.int64(641),
 'like human': np.int64(1319),
 'movie': np.int64(1495),
 'win': np.int64(2448),
 'best': np.int64(180),
 'best comedy': np.int64(181),
 'genius': np.int64(853),
 'work': np.int64(2462),
 'say': np.int64(1949),
 'degree': np.int64(508),
 'saw': np.int64(1948),
 'nothing': np.int64(1541),
 'well': np.int64(2438),
 'funny': np.int64(836),
 'instagram': np.int64(1125),
 'positivity': np.int64(1684),
 'contagious': np.int64(397),
 'smile': np.int64(2064),
 'impossible': np.int64(1069),
 'feel': np.int64(774),
 'positivity like': np.int64(1690),
 'impossible feel': np.int64(1070),
 'watch content': np.int64(2424),
 'create': np.int64(425),
 'powerful': np.int64(1716),
 'picture': np.int64(1634),
 'let': np.int64(1283),
 'ever': np.int64(697),
 'help': np.int64(974),
 'hand': np.int64(936),
 'let know': np.int64(1284),
 'ever need': np.int64(699),
 'ability': np.int64(1),
 'amaze': np.int64(55),
 'image': np.int64(1054),
 'narrative': np.int64(1507),
 'limit': np.int64(1328),
 'vlo': np.int64(2400),
 'dedication': np.int64(495),
 'craft': np.int64(422),
 'evident': np.int64(716),
 'every': np.int64(700),
 'frame': np.int64(814),
 'dedication craft': np.int64(497),
 'evident every': np.int64(717),
 'achieve': np.int64(21),
 'anything': np.int64(68),
 'mother': np.int64(1490),
 'fuck': np.int64(830),
 'er': np.int64(684),
 'stupid': np.int64(2162),
 'really': np.int64(1842),
 'hard': np.int64(948),
 'take': np.int64(2211),
 'take eye': np.int64(2214),
 'tr': np.int64(2313),
 'kokonoi': np.int64(1224),
 'soytan': np.int64(2099),
 'oh': np.int64(1551),
 'beauty': np.int64(158),
 'refresh': np.int64(1854),
 'short': np.int64(2030),
 'people': np.int64(1600),
 'smart': np.int64(2060),
 'short people': np.int64(2031),
 'lol': np.int64(1340),
 'boy': np.int64(214),
 'change': np.int64(297),
 'find': np.int64(788),
 'believe': np.int64(172),
 'pretty': np.int64(1732),
 'enough': np.int64(671),
 'refugee': np.int64(1855),
 'critical': np.int64(439),
 'historical': np.int64(996),
 'religion': np.int64(1869),
 'justify': np.int64(1184),
 'act': np.int64(23),
 'imperialism': np.int64(1066),
 'critical historical': np.int64(441),
 'historical use': np.int64(1001),
 'use religion': np.int64(2375),
 'religion justify': np.int64(1873),
 'dawg': np.int64(475),
 'woman': np.int64(2457),
 'suffer': np.int64(2169),
 'dawg want': np.int64(476),
 'want make': np.int64(2412),
 'unwanted': np.int64(2361),
 'call': np.int64(262),
 'material': np.int64(1439),
 'sexual': np.int64(2002),
 'nature': np.int64(1514),
 'sexual nature': np.int64(2006),
 'nation': np.int64(1508),
 'good': np.int64(886),
 'tui': np.int64(2344),
 'ki': np.int64(1200),
 'fake': np.int64(757),
 'news': np.int64(1528),
 'reach': np.int64(1835),
 'fake news': np.int64(758),
 'prude': np.int64(1773),
 'institution': np.int64(1130),
 'would': np.int64(2480),
 'great': np.int64(906),
 'transparency': np.int64(2317),
 'religious institution': np.int64(1889),
 'natural': np.int64(1512),
 'royalty': np.int64(1937),
 'authenticity': np.int64(115),
 'breath': np.int64(219),
 'fresh': np.int64(822),
 'air': np.int64(44),
 'digital': np.int64(543),
 'keep': np.int64(1187),
 'continue': np.int64(404),
 'inspire': np.int64(1120),
 'authenticity breath': np.int64(116),
 'breath fresh': np.int64(220),
 'fresh air': np.int64(823),
 'air digital': np.int64(45),
 'digital world': np.int64(544),
 'world keep': np.int64(2473),
 'increase': np.int64(1081),
 'polarization': np.int64(1649),
 'discourse': np.int64(555),
 'stifle': np.int64(2134),
 'brighten': np.int64(226),
 'anyone': np.int64(65),
 'smile brighten': np.int64(2065),
 'brighten anyone': np.int64(227),
 'anyone day': np.int64(66),
 'resistant': np.int64(1905),
 'address': np.int64(27),
 'case': np.int64(278),
 'child': np.int64(331),
 'abuse': np.int64(11),
 'institution resistant': np.int64(1132),
 'inspiring': np.int64(1123),
 'craft truly': np.int64(423),
 'truly inspiring': np.int64(2339),
 'thanks': np.int64(2253),
 'everyone': np.int64(709),
 'come': np.int64(360),
 'walk': np.int64(2408),
 'bully': np.int64(248),
 'dog': np.int64(584),
 'group': np.int64(911),
 'relatable': np.int64(1864),
 'loser': np.int64(1353),
 'embarrass': np.int64(635),
 'complete': np.int64(381),
 'waste': np.int64(2420),
 'waste time': np.int64(2422),
 'hindu': np.int64(994),
 'channel': np.int64(299),
 'knowledge': np.int64(1222),
 'enlightenment': np.int64(669),
 'share': np.int64(2014),
 'expertise': np.int64(733),
 'enlightenment thank': np.int64(670),
 'thank share': np.int64(2249),
 'share expertise': np.int64(2016),
 'cute': np.int64(458),
 'fantastic': np.int64(762),
 'get enough': np.int64(860),
 'enough content': np.int64(672),
 'keep fantastic': np.int64(1191),
 'gold': np.int64(879),
 'end': np.int64(652),
 'guilt': np.int64(924),
 'fear': np.int64(770),
 'guilt fear': np.int64(925),
 'friend': np.int64(824),
 'storytelling': np.int64(2142),
 'captivating': np.int64(271),
 'eager': np.int64(606),
 'happen': np.int64(942),
 'next': np.int64(1529),
 'storytelling like': np.int64(2146),
 'follow': np.int64(801),
 'online': np.int64(1558),
 'give': np.int64(869),
 'kindness': np.int64(1206),
 'empathy': np.int64(643),
 'interaction': np.int64(1142),
 'audience': np.int64(112),
 'genuinely': np.int64(856),
 'care': np.int64(274),
 'kindness empathy': np.int64(1208),
 'empathy shine': np.int64(646),
 'shine interaction': np.int64(2024),
 'interaction audience': np.int64(1143),
 'politics': np.int64(1667),
 'prioritize': np.int64(1735),
 'protection': np.int64(1769),
 'suppress': np.int64(2194),
 'undermines': np.int64(2353),
 'government transparency': np.int64(900),
 'go': np.int64(871),
 'away': np.int64(131),
 'outside': np.int64(1574),
 'attack': np.int64(106),
 'bring': np.int64(234),
 'resilience': np.int64(1902),
 'face': np.int64(748),
 'challenge': np.int64(291),
 'testament': np.int64(2241),
 'character': np.int64(314),
 'resilience face': np.int64(1903),
 'face challenge': np.int64(750),
 'testament character': np.int64(2243),
 'capture': np.int64(272),
 'bet': np.int64(185),
 'freak': np.int64(816),
 'private': np.int64(1740),
 'snort': np.int64(2068),
 'laugh': np.int64(1244),
 'reason': np.int64(1843),
 'cheek': np.int64(323),
 'hurt': np.int64(1041),
 'grin': np.int64(910),
 'room': np.int64(1934),
 'pant': np.int64(1580),
 'financial': np.int64(787),
 'interest': np.int64(1145),
 'institution prioritize': np.int64(1131),
 'cherish': np.int64(325),
 'memory': np.int64(1459),
 'warm': np.int64(2415),
 'style': np.int64(2163),
 'iconic': np.int64(1044),
 'perfect': np.int64(1605),
 'journey': np.int64(1170),
 'youtube': np.int64(2495),
 'example': np.int64(720),
 'aspire': np.int64(95),
 'creator': np.int64(432),
 'experience': np.int64(732),
 'aspire content': np.int64(96),
 'content creator': np.int64(400),
 'place': np.int64(1638),
 'thanks make': np.int64(2254),
 'make tiktok': np.int64(1413),
 'tiktok good': np.int64(2281),
 'good place': np.int64(888),
 'stop': np.int64(2136),
 'election': np.int64(627),
 'kore': np.int64(1225),
 'impressed': np.int64(1072),
 'energy': np.int64(660),
 'level': np.int64(1286),
 'source': np.int64(2091),
 'source personal': np.int64(2097),
 'growth enlightenment': np.int64(914),
 'internet': np.int64(1149),
 'make internet': np.int64(1402),
 'internet good': np.int64(1150),
 'president': np.int64(1728),
 'donald': np.int64(589),
 'trump': np.int64(2341),
 'radical': np.int64(1822),
 'islamic': np.int64(1156),
 'terrorism': np.int64(2239),
 'donald trump': np.int64(590),
 'radical islamic': np.int64(1823),
 'islamic terrorism': np.int64(1157),
 'job': np.int64(1166),
 'market': np.int64(1434),
 'oversaturated': np.int64(1576),
 'employment': np.int64(648),
 'role': np.int64(1931),
 'model': np.int64(1483),
 'spread': np.int64(2110),
 'happiness': np.int64(943),
 'role model': np.int64(1932),
 'story': np.int64(2140),
 'celebration': np.int64(288),
 'love story': np.int64(1365),
 'shoe': np.int64(2029),
 'wear': np.int64(2432),
 'detail': np.int64(532),
 'today': np.int64(2294),
 'look great': np.int64(1348),
 'complex': np.int64(382),
 'topic': np.int64(2303),
 'simple': np.int64(2043),
 'rare': np.int64(1830),
 'excellent': np.int64(723),
 'appreciate': np.int64(72),
 'support': np.int64(2188),
 'encouragement': np.int64(651),
 'express': np.int64(743),
 'support encouragement': np.int64(2189),
 'perpetuate': np.int64(1608),
 'gender': np.int64(849),
 'critical role': np.int64(443),
 'role religion': np.int64(1933),
 'religion perpetuate': np.int64(1876),
 'praise': np.int64(1718),
 'history': np.int64(1002),
 'scientific': np.int64(1955),
 'progress': np.int64(1758),
 'vote': np.int64(2402),
 'toke': np.int64(2297),
 'na': np.int64(1505),
 'skeptical': np.int64(2053),
 'text': np.int64(2245),
 'religious text': np.int64(1893),
 'troll': np.int64(2328),
 'three': np.int64(2275),
 'main': np.int64(1385),
 'line': np.int64(1331),
 'comment': np.int64(371),
 'laughter': np.int64(1250),
 'champion': np.int64(295),
 'book': np.int64(208),
 'read': np.int64(1837),
 'sure': np.int64(2199),
 'big': np.int64(192),
 'deal': np.int64(485),
 'wow': np.int64(2482),
 'nice': np.int64(1530),
 'dear': np.int64(486),
 'wow nice': np.int64(2484),
 'despite': np.int64(526),
 'year': np.int64(2489),
 'promotion': np.int64(1763),
 'despite year': np.int64(528),
 'year dedication': np.int64(2490),
 'attention': np.int64(108),
 'impressive': np.int64(1073),
 'little': np.int64(1335),
 'thing': np.int64(2260),
 'difference': np.int64(538),
 'attention detail': np.int64(109),
 'little thing': np.int64(1336),
 'video make': np.int64(2387),
 'firework': np.int64(793),
 'light': np.int64(1302),
 'light day': np.int64(1303),
 'account': np.int64(19),
 'real': np.int64(1839),
 'treasure': np.int64(2320),
 'feed': np.int64(773),
 'instagram feed': np.int64(1127),
 'master': np.int64(1435),
 'define': np.int64(505),
 'without': np.int64(2454),
 'social': np.int64(2069),
 'medium': np.int64(1452),
 'sensation': np.int64(1983),
 'social medium': np.int64(2072),
 'misuse': np.int64(1478),
 'emergency': np.int64(637),
 'declaration': np.int64(490),
 'bypass': np.int64(260),
 'legislative': np.int64(1280),
 'threatens': np.int64(2274),
 'democracy': np.int64(514),
 'misuse emergency': np.int64(1479),
 'emergency declaration': np.int64(638),
 'declaration bypass': np.int64(491),
 'bypass legislative': np.int64(261),
 'sex': np.int64(2000),
 'straight': np.int64(2148),
 'gorgeous': np.int64(893),
 'think straight': np.int64(2265),
 'straight around': np.int64(2149),
 'passion': np.int64(1587),
 'screen': np.int64(1958),
 'clear': np.int64(348),
 'moment': np.int64(1484),
 'love every': np.int64(1361),
 'every moment': np.int64(703),
 'bitch': np.int64(195),
 'look like': np.int64(1349),
 'behind': np.int64(169),
 'far': np.int64(764),
 'hot': np.int64(1021),
 'significant': np.int64(2040),
 'staff': np.int64(2116),
 'turnover': np.int64(2346),
 'rate': np.int64(1831),
 'company': np.int64(376),
 'result': np.int64(1912),
 'environment': np.int64(681),
 'staff turnover': np.int64(2117),
 'turnover rate': np.int64(2347),
 'whisper': np.int64(2442),
 'perfection': np.int64(1606),
 'presence': np.int64(1725),
 'facebook': np.int64(751),
 'fill': np.int64(784),
 'supernatural': np.int64(2184),
 'claim': np.int64(344),
 'continually': np.int64(403),
 'determination': np.int64(535),
 'figure': np.int64(783),
 'community': np.int64(375),
 'religious community': np.int64(1886),
 'send': np.int64(1981),
 'try': np.int64(2343),
 'trade': np.int64(2314),
 'one': np.int64(1553),
 'captain': np.int64(268),
 'hilarity': np.int64(990),
 'infrastructure': np.int64(1101),
 'expose': np.int64(742),
 'cyberattacks': np.int64(459),
 'cybersecurity': np.int64(460),
 'measure': np.int64(1448),
 'critical infrastructure': np.int64(442),
 'cybersecurity measure': np.int64(461),
 'veteran': np.int64(2380),
 'mental': np.int64(1461),
 'health': np.int64(958),
 'treatment': np.int64(2324),
 'neglect': np.int64(1519),
 'lead': np.int64(1257),
 'high': np.int64(983),
 'suicide': np.int64(2171),
 'mental health': np.int64(1462),
 'health treatment': np.int64(963),
 'lead high': np.int64(1260),
 'success': np.int64(2167),
 'set': np.int64(1995),
 'standard': np.int64(2121),
 'set high': np.int64(1999),
 'high standard': np.int64(987),
 'nigga': np.int64(1532),
 'politicization': np.int64(1666),
 'decision': np.int64(488),
 'crisis': np.int64(437),
 'safety': np.int64(1944),
 'public health': np.int64(1776),
 'undermines public': np.int64(2354),
 'public safety': np.int64(1779),
 'india': np.int64(1085),
 'grateful': np.int64(903),
 'enthusiasm': np.int64(678),
 'passion life': np.int64(1592),
 'life contagious': np.int64(1296),
 'kindness make': np.int64(1210),
 'make world': np.int64(1417),
 'world good': np.int64(2472),
 'awe': np.int64(132),
 'skill': np.int64(2055),
 'girl': np.int64(868),
 'sense': np.int64(1984),
 'superiority': np.int64(2183),
 'among': np.int64(57),
 'believer': np.int64(174),
 'bad': np.int64(139),
 'bad day': np.int64(140),
 'chef': np.int64(324),
 'bangladesh': np.int64(144),
 'loose': np.int64(1350),
 'country': np.int64(419),
 'grand': np.int64(902),
 'engross': np.int64(666),
 'start': np.int64(2126),
 'finish': np.int64(791),
 'well do': np.int64(2439),
 'start finish': np.int64(2127),
 'failure': np.int64(753),
 'systemic': np.int64(2209),
 'racial': np.int64(1816),
 'disparity': np.int64(562),
 'injustice': np.int64(1103),
 'discrimination': np.int64(557),
 'failure address': np.int64(754),
 'address systemic': np.int64(28),
 'perpetuate injustice': np.int64(1609),
 'money': np.int64(1485),
 'open': np.int64(1560),
 'sexually': np.int64(2008),
 'gentle': np.int64(854),
 'thousand': np.int64(2269),
 'could': np.int64(416),
 'regard': np.int64(1856),
 'kitty': np.int64(1214),
 'sometimes': np.int64(2080),
 'promote': np.int64(1761),
 'idea': np.int64(1046),
 'authoritarian': np.int64(126),
 'religion sometimes': np.int64(1878),
 'sometimes promote': np.int64(2084),
 'favor': np.int64(767),
 'magnificence': np.int64(1383),
 'youtube world': np.int64(2497),
 'gift': np.int64(863),
 'capture moment': np.int64(273),
 'enjoyable': np.int64(668),
 'aspect': np.int64(93),
 'shine every': np.int64(2023),
 'make difference': np.int64(1395),
 'long': np.int64(1341),
 'hour': np.int64(1022),
 'constant': np.int64(394),
 'stress': np.int64(2152),
 'chosen': np.int64(335),
 'occupation': np.int64(1544),
 'terrible': np.int64(2238),
 'effect': np.int64(621),
 'long hour': np.int64(1342),
 'hour constant': np.int64(1023),
 'stress chosen': np.int64(2154),
 'beat': np.int64(153),
 'shame': np.int64(2012),
 'religion lead': np.int64(1874),
 'lead sense': np.int64(1261),
 'agree': np.int64(42),
 'rapist': np.int64(1828),
 'scum': np.int64(1962),
 'earth': np.int64(609),
 'people would': np.int64(1604),
 'would agree': np.int64(2481),
 'agree rapist': np.int64(43),
 'rapist scum': np.int64(1829),
 'scum earth': np.int64(1963),
 'foreign': np.int64(805),
 'domestic': np.int64(588),
 'art': np.int64(81),
 'form': np.int64(808),
 'gallery': np.int64(844),
 'storytelling art': np.int64(2144),
 'art form': np.int64(82),
 'dream': np.int64(597),
 'passion evident': np.int64(1590),
 'every video': np.int64(706),
 'live dream': np.int64(1338),
 'often': np.int64(1549),
 'appointment': np.int64(71),
 'individual': np.int64(1089),
 'important': np.int64(1067),
 'position': np.int64(1677),
 'political patronage': np.int64(1660),
 'friendship': np.int64(825),
 'strength': np.int64(2151),
 'lucky': np.int64(1378),
 'friendship source': np.int64(827),
 'source strength': np.int64(2098),
 'pal': np.int64(1579),
 'fat': np.int64(765),
 'ugly': np.int64(2349),
 'fat ugly': np.int64(766),
 'even': np.int64(694),
 'pathetic': np.int64(1598),
 'tell': np.int64(2233),
 'subscription': np.int64(2166),
 'adventure': np.int64(37),
 'wait': np.int64(2406),
 'explore': np.int64(741),
 'many': np.int64(1428),
 'career': np.int64(275),
 'poor': np.int64(1669),
 'economy': np.int64(617),
 'difficult': np.int64(540),
 'near': np.int64(1515),
 'something': np.int64(2078),
 'remarkable': np.int64(1895),
 'seem': np.int64(1977),
 'extraordinary': np.int64(745),
 'talent make': np.int64(2218),
 'make even': np.int64(1397),
 'trove': np.int64(2330),

In [95]:
X_test=tfidf.transform(X_test).toarray()

In [96]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [97]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
models = {
    "MultinomialNB": MultinomialNB(),
    "LogisticRegression": LogisticRegression(),
    "LinearSVC": LinearSVC(),
    "RandomForest": RandomForestClassifier()
}

In [98]:
models

{'MultinomialNB': MultinomialNB(),
 'LogisticRegression': LogisticRegression(),
 'LinearSVC': LinearSVC(),
 'RandomForest': RandomForestClassifier()}

In [99]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [101]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

for name, model in models.items():
    print(f"\n{name} training...")

    # Train the model
    model.fit(X_train, y_train)

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Training metrics
    print("\n--- Training Metrics ---")
    print("Accuracy:", accuracy_score(y_train, y_train_pred))
    print("Precision:", precision_score(y_train, y_train_pred, pos_label=1))
    print("Recall:", recall_score(y_train, y_train_pred, pos_label=1))
    print("F1-score:", f1_score(y_train, y_train_pred, pos_label=1))

    # Testing metrics
    print("\n--- Testing Metrics ---")
    print("Accuracy:", accuracy_score(y_test, y_test_pred))
    print("Precision:", precision_score(y_test, y_test_pred, pos_label=1))
    print("Recall:", recall_score(y_test, y_test_pred, pos_label=1))
    print("F1-score:", f1_score(y_test, y_test_pred, pos_label=1))

    print("--"*20)
    print()

MultinomialNB training...

--- Training Metrics ---
Accuracy: 0.9117283950617284
Precision: 0.9063860667634253
Recall: 0.9359310603222181
F1-score: 0.9209216589861751

--- Testing Metrics ---
Accuracy: 0.8691358024691358
Precision: 0.8528138528138528
Recall: 0.9120370370370371
F1-score: 0.8814317673378076
----------------------------------------


LogisticRegression training...

--- Training Metrics ---
Accuracy: 0.9106995884773662
Precision: 0.8969804618117229
Recall: 0.9460472086923941
F1-score: 0.9208606856309264

--- Testing Metrics ---
Accuracy: 0.8683127572016461
Precision: 0.8485714285714285
Recall: 0.9166666666666666
F1-score: 0.8813056379821959
----------------------------------------


LinearSVC training...

--- Training Metrics ---
Accuracy: 0.9409465020576132
Precision: 0.9353070175438597
Recall: 0.9587860621955788
F1-score: 0.9469010175763182

--- Testing Metrics ---
Accuracy: 0.8650205761316873
Precision: 0.8579881656804734
Recall: 0.8950617283950617
F1-score: 0.8761329305135952
----------------------------------------


RandomForest training...

--- Training Metrics ---
Accuracy: 0.9761316872427983
Precision: 0.9733036707452726
Recall: 0.9835144248782316
F1-score: 0.9783824077525158

--- Testing Metrics ---
Accuracy: 0.8460905349794239
Precision: 0.8374816983894583
Recall: 0.8827160493827161
F1-score: 0.859504132231405
----------------------------------------

In [102]:
models = {
    "MultinomialNB": MultinomialNB(),
    "LogisticRegression": LogisticRegression(),
}

In [103]:
from sklearn.model_selection import GridSearchCV

In [104]:
params = {
    "MultinomialNB": [
        {
            'alpha': [0.1, 0.5, 1.0, 1.5, 2.0],   # smoothing parameter
            'fit_prior': [True, False]           # whether to learn class prior probabilities
        }
    ],
    
    "LogisticRegression": [
        {
            'C': [0.01, 0.1, 1, 10],             # inverse of regularization strength
            'penalty': ['l1', 'l2'],             # L1 = Lasso, L2 = Ridge
            'solver': ['liblinear'],             # solver compatible with L1 & L2
            'max_iter': [500]                     # ensure convergence
        }
    ]
}

In [105]:
params

{'MultinomialNB': [{'alpha': [0.1, 0.5, 1.0, 1.5, 2.0],
   'fit_prior': [True, False]}],
 'LogisticRegression': [{'C': [0.01, 0.1, 1, 10],
   'penalty': ['l1', 'l2'],
   'solver': ['liblinear'],
   'max_iter': [500]}]}

In [107]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

for name, model in models.items():
    print(f"\n{name} training...")

    # Train the model
    grid=GridSearchCV(estimator=model,param_grid=params[name],cv=5,scoring='f1',n_jobs=-1)

    grid.fit(X_train,y_train)

    # Predictions
    y_train_pred = grid.predict(X_train)
    y_test_pred = grid.predict(X_test)

    # Training metrics
    print("\n--- Training Metrics ---")
    print("Accuracy:", accuracy_score(y_train, y_train_pred))
    print("Precision:", precision_score(y_train, y_train_pred, pos_label=1))
    print("Recall:", recall_score(y_train, y_train_pred, pos_label=1))
    print("F1-score:", f1_score(y_train, y_train_pred, pos_label=1))

    # Testing metrics
    print("\n--- Testing Metrics ---")
    print("Accuracy:", accuracy_score(y_test, y_test_pred))
    print("Precision:", precision_score(y_test, y_test_pred, pos_label=1))
    print("Recall:", recall_score(y_test, y_test_pred, pos_label=1))
    print("F1-score:", f1_score(y_test, y_test_pred, pos_label=1))

    print()
    print("best params:",grid.best_params_)
    print("--"*20)
    print()

MultinomialNB training...

--- Training Metrics ---
Accuracy: 0.9117283950617284
Precision: 0.9063860667634253
Recall: 0.9359310603222181
F1-score: 0.9209216589861751

--- Testing Metrics ---
Accuracy: 0.8691358024691358
Precision: 0.8528138528138528
Recall: 0.9120370370370371
F1-score: 0.8814317673378076

best params: {'alpha': 1.0, 'fit_prior': True}
----------------------------------------


LogisticRegression training...

--- Training Metrics ---
Accuracy: 0.9104938271604939
Precision: 0.8966619318181818
Recall: 0.9460472086923941
F1-score: 0.9206927985414768

--- Testing Metrics ---
Accuracy: 0.8666666666666667
Precision: 0.8461538461538461
Recall: 0.9166666666666666
F1-score: 0.88

best params: {'C': 1, 'max_iter': 500, 'penalty': 'l2', 'solver': 'liblinear'}
----------------------------------------

In [109]:
model=LogisticRegression(C=1,max_iter=500,penalty='l2',solver='liblinear')

model.fit(X_train,y_train)

model

LogisticRegression(C=1, max_iter=500, solver='liblinear')

In [110]:
y_pred=model.predict(X_test)

In [113]:
range(len(y_test))

range(0, 1215)

In [120]:
tfidf

TfidfVectorizer(max_features=2500, ngram_range=(1, 2))

In [122]:
def clean_message(text):
    cleaned=re.sub(r'[^a-zA-Z]',' ',text)

    cleaned=cleaned.lower()

    cleaned=cleaned.split()
    
    pos_tags=nltk.pos_tag(cleaned)

    cleaned=[lemmatizer.lemmatize(word,pos=get_wordnet_pos(pos)) for word,pos in pos_tags if word not in stopwords_list]
    cleaned=' '.join(cleaned)

    return cleaned

In [123]:
text = "The cats are running faster than the dogs!"
clean_message(text)

'cat run faster dog'

In [147]:
def predict(text):
    cleaned=clean_message(text)
    X_new=tfidf.transform([cleaned])
    pred=model.predict(X_new)

    if pred[0]==1:
        return 'harrasment'
    else:
        return 'normal'

In [150]:
user_msg = input("Enter a message: ")

prediction=predict(user_msg)
prediction

'normal'

In [86]:
df.head(10)

                                                text  label
0  Ten outside soon doctor shake everyone treatme...      0
1  my life has come to a standstill and at this p...      0
2         girl this nigga make me sick to my stomach      1
3                                   I wanna fuck you      1
4  Oh hey, you should be ashamed of your disgusti...      0
5  Haha isn't route running part of the position?...      1
6  Racism is when u select yur white clothes to w...      1
7  Who are islamists? Those who fully follow the ...      1
8  Male action movies...ehhhh @That_Damn_Ram Not ...      1
9                   Wishing my arena partner was on.      0